//铁砧兼容性调整(调整铁砧安装文件，部分规则修改由替换式改为插入式，使其兼容EET和其它MOD)

ACTION_IF (GAME_IS ~eet~) THEN BEGIN

  COPY ~ImprovedAnvil/Setup-ImprovedAnvil.tp2~ ~ImprovedAnvil/Setup-ImprovedAnvil.tp2~
    REPLACE_TEXTUALLY ~bg2ee~ ~bg2ee eet~
  BUT_ONLY

  COPY ~lzbgmod/IATweaksByLZ/resources/creatures/vanilla/imoen10.cre~   ~ImprovedAnvil/resources/creatures/vanilla~      //EET版SOA开局要修改这个，否则卡住，BG2EE则不用 

// 列表
ACTION_DEFINE_ARRAY mod_directory_list BEGIN
    ~ImprovedAnvil/~
	
	~ImprovedAnvil/lib/areas~ ~ImprovedAnvil/lib/core~ ~ImprovedAnvil/lib/creatures~ ~ImprovedAnvil/lib/dialogues~
	~ImprovedAnvil/lib/effects~ ~ImprovedAnvil/lib/items~ ~ImprovedAnvil/lib/kits~ ~ImprovedAnvil/lib/scripts~
	~ImprovedAnvil/lib/spells~ ~ImprovedAnvil/lib/stores~ ~ImprovedAnvil/lib/tpa~
	//~ImprovedAnvil/lib/tables~
	
	~ImprovedAnvil/resources/dlg~ ~ImprovedAnvil/resources/intermediate~
	
	~ImprovedAnvil/scripts/areas~ ~ImprovedAnvil/scripts/beholders~ ~ImprovedAnvil/scripts/clerics~ ~ImprovedAnvil/scripts/common~
	~ImprovedAnvil/scripts/cutscenes~ ~ImprovedAnvil/scripts/demons~ ~ImprovedAnvil/scripts/dragons~
	
	~ImprovedAnvil/scripts/encounters/bridge~ ~ImprovedAnvil/scripts/encounters/brynnlaw~ ~ImprovedAnvil/scripts/encounters/dearnise~ ~ImprovedAnvil/scripts/encounters/docks~
	~ImprovedAnvil/scripts/encounters/druid_grove~ ~ImprovedAnvil/scripts/encounters/druid_quests~ ~ImprovedAnvil/scripts/encounters/firkraag_dungeon~ ~ImprovedAnvil/scripts/encounters/forest_of_myr~
	~ImprovedAnvil/scripts/encounters/forest_of_tethir~ ~ImprovedAnvil/scripts/encounters/graveyard~ ~ImprovedAnvil/scripts/encounters/hell~ ~ImprovedAnvil/scripts/encounters/irenicus_dungeon~
	~ImprovedAnvil/scripts/encounters/oasis~ ~ImprovedAnvil/scripts/encounters/planar_prison~ ~ImprovedAnvil/scripts/encounters/planar_sphere~ ~ImprovedAnvil/scripts/encounters/pocket_plane~
	~ImprovedAnvil/scripts/encounters/random~ ~ImprovedAnvil/scripts/encounters/saradush~ ~ImprovedAnvil/scripts/encounters/sendai_enclave~ ~ImprovedAnvil/scripts/encounters/slums~
	~ImprovedAnvil/scripts/encounters/small_teeth_pass~ ~ImprovedAnvil/scripts/encounters/spellhold~ ~ImprovedAnvil/scripts/encounters/suldanesselar~ ~ImprovedAnvil/scripts/encounters/temple~
	~ImprovedAnvil/scripts/encounters/temple_ruins~ ~ImprovedAnvil/scripts/encounters/the_four~ ~ImprovedAnvil/scripts/encounters/throne_of_bhaal~ ~ImprovedAnvil/scripts/encounters/trademeet~
	~ImprovedAnvil/scripts/encounters/umar_hills~ ~ImprovedAnvil/scripts/encounters/underdark~ ~ImprovedAnvil/scripts/encounters/vagrant_quests~ ~ImprovedAnvil/scripts/encounters/watchers_keep~
	~ImprovedAnvil/scripts/encounters/waukeen_promenade~ ~ImprovedAnvil/scripts/encounters/yaga_shura_keep~
	
	~ImprovedAnvil/scripts/genie~ ~ImprovedAnvil/scripts/golems~ ~ImprovedAnvil/scripts/liches~ ~ImprovedAnvil/scripts/lycanthropes~
	~ImprovedAnvil/scripts/mages~ ~ImprovedAnvil/scripts/misc~ ~ImprovedAnvil/scripts/monsters~ ~ImprovedAnvil/scripts/niether~
	~ImprovedAnvil/scripts/npc~ ~ImprovedAnvil/scripts/patches~ ~ImprovedAnvil/scripts/rakshasa~ ~ImprovedAnvil/scripts/spiders~
	~ImprovedAnvil/scripts/transitions~ ~ImprovedAnvil/scripts/undead~
END

ACTION_DEFINE_ARRAY extension_list BEGIN
    ~baf~
    ~d~
    ~tp2~
    ~tpa~
	~tph~
	~tpp~
END

ACTION_PHP_EACH mod_directory_list AS index1 => mod_dir BEGIN

    //PRINT ~        正在处理的目录: %mod_dir%~

    ACTION_PHP_EACH extension_list AS index2 => ext BEGIN

        // 根据mod_directory_list，进入对应文件夹找后缀extension_list文件
        ACTION_BASH_FOR ~%mod_dir%~ EVALUATE_REGEXP ~^.+\.%ext%$~ BEGIN
            
			// 每个新文件开始时，强制将全局计数器清零，掐断跨文件污染
            OUTER_SET match_count = 0

            //注意：下面这句判断可以去掉，加上是为了使weidu窗口运行时更干净，只显示那些改过的。
            // 匹配任意"CHAPTER"加,
            ACTION_IF FILE_CONTAINS_EVALUATED (~%BASH_FOR_FILESPEC%~ ~"CHAPTER"[ %TAB%]*,~) BEGIN

                // COPY - 纯读入内存，不污染硬盘
                COPY - ~%BASH_FOR_FILESPEC%~ ~.../eet_temp_patch~
		  
                    // 防止IncrementGlobal("CHAPTER",GLOBAL,1)这类被误改
                    REPLACE_TEXTUALLY ~IncrementGlobal~ ~IncrementReplaceMe~
    
                    // 匹配SetGlobal, Global, GlobalGT, GlobalLT, SG, G, GGT, GLT。例： %MATCH1% = Global("CHAPTER","GLOBAL",   %MATCH2% = 2（经过转换后为%eet_chapter%即2+12）   %MATCH3% = )
                    REPLACE_EVALUATE CASE_INSENSITIVE ~\([A-Za-z]*G[A-Za-z]*([ %TAB%]*"CHAPTER"[ %TAB%]*,?[ %TAB%]*"?G?L?O?B?A?L?"?[ %TAB%]*,[ %TAB%]*\)\([0-9]+\)\([ %TAB%]*)\)~ BEGIN
        
		                // 三元运算符 ?   是整数执行MATCH2 + 12，否则不变
                        SET eet_chapter = IS_AN_INT MATCH2 ? (MATCH2 + 12) : MATCH2
        
                        // 仅在真正触发章节转换时，累计匹配次数
                        SET match_count += 1
        
                    END ~%MATCH1%%eet_chapter%%MATCH3%~ 
    
	                // 还原防御改名
                    REPLACE_TEXTUALLY ~IncrementReplaceMe~ ~IncrementGlobal~
					
                BUT_ONLY
				
                // 只有当前文件在内存里确实被改变过，才写入硬盘
                ACTION_IF (match_count > 0) BEGIN
				
                    // 转换成功打印日志
                    PRINT ~    --> 发现文件 (%ext%) 且成功转换 [%match_count% 处] 章节: %BASH_FOR_FILESPEC%~
    
                    // 把内存里改动过的文件写回硬盘
                    COPY ~.../eet_temp_patch~ ~%BASH_FOR_FILESPEC%~
                END
            END
        END
    END
END

END

COPY ~lzbgmod/IATweaksByLZ/lib/core/ids.tph~   ~ImprovedAnvil/lib/core~         //一些规则修改由替换改插入

COPY ~lzbgmod/IATweaksByLZ/lib/core/2da_1.tph~   ~ImprovedAnvil/lib/core/2da.tph~     //下面SPAWNGRP.2DA相关修改调到这里
//COPY ~lzbgmod/IATweaksByLZ/lib/core/2da.tph~   ~ImprovedAnvil/lib/core~         //铁砧屏蔽了许愿出双倍时停高捷，修改后解除，下面SPAWNGRP.2DA相关修改调到这里

COPY ~lzbgmod/IATweaksByLZ/lib/areas/05_worldmap.tph~   ~ImprovedAnvil/lib/areas~     //和EEUITweaks、其它MOD图片冲突修复

//已改为改写2da.tph里的相关代码
//和疯神王座、失落女神的呼唤、暗潮涌动、巴洛维亚的血腥骗局冲突修复，铁砧安装方式是直接COPY到override，2da列范围原版BG2EE同原版EET同安装铁砧后的BG2EE或EET，其它MOD需要添加列
//COPY ~lzbgmod/IATweaksByLZ/CRASHFIX/SPAWNGRP.2DA~   ~ImprovedAnvil/resources/2da~

// 替换d文件的数字标签，防止某个dlg文件被其它MOD修改后数字标签变化，安装铁砧时编译同名d文件提示标签被占用报错。
OUTER_SPRINT ia_dlg_dir ~ImprovedAnvil/resources/dlg~ 

ACTION_DEFINE_ASSOCIATIVE_ARRAY ia_d_files_dict BEGIN
    ~CORNEIL~      => ~CORNEIL.D~
	~PPSAEM3~      => ~PPSAEM3.D~
    ~SHOP03~       => ~SHOP03.D~
	~UDDEMON~      => ~UDDEMON.D~
	
	//~CECHALLE_DQ~  => ~CECHALLE_DQ.D~
    //~PPDRA2~       => ~PPDRA2.D~
    //~UHRANG01~     => ~UHRANG01.D~
	
	//~MURCRAG~      => ~MURCRAG.D~
END

ACTION_PHP_EACH ia_d_files_dict AS res_name => d_filename BEGIN
	// 自动拼装当前要处理的 .d 文件的完整硬盘绝对路径
    OUTER_SPRINT BASH_FOR_FILESPEC ~%ia_dlg_dir%/%d_filename%~
	// 提取出不含后缀的纯资源名（RESNAME），用作后续文字标签的前缀
    OUTER_SPRINT BASH_FOR_RES      ~%res_name%~

    COPY - ~%BASH_FOR_FILESPEC%~ ~.../ia_d_patch~
		// 清空局部数组，并将计数器归零，彻底掐断跨文件的标签数据污染
        CLEAR_ARRAY local_defined_labels
        SET label_index = 0
		
		// 锁定有 "THEN BEGIN 数字" 的合法上下文，利用圆括号把纯数字捕获到 %MATCH1% 中。
        // 末尾原样放回 %MATCH0%，实现对正文内容 0 修改的“无痕浏览”。
        REPLACE_EVALUATE CASE_INSENSITIVE ~[ %TAB%]THEN[ %TAB%]+BEGIN[ %TAB%]+\([0-9]+\)~ BEGIN
			// 将当前揪出的数字（如 73）存入名为 local_defined_labels 的名单（数组）中
            SPRINT $local_defined_labels(~%label_index%~) ~%MATCH1%~
            SET label_index += 1
        END ~%MATCH0%~
		
		REPLACE_EVALUATE CASE_INSENSITIVE ~\([ %TAB%]THEN[ %TAB%]+BEGIN[ %TAB%]+\)\([0-9]+\)\([ %TAB%]*\r?\n?\)~ BEGIN
			// 每次成功改造节点时，在 WeiDU 窗口实时打印变动细节
            PATCH_PRINT ~%d_filename%数字标签替换THEN BEGIN %MATCH2%->THEN BEGIN ia_%BASH_FOR_RES%_%MATCH2%~
        END ~%MATCH1%ia_%BASH_FOR_RES%_%MATCH2%%MATCH3%~
		
		// 拿着名单里登记好的数字进行轮询，只有指向新节点的 GOTO 才允许加前缀
		PHP_EACH local_defined_labels AS info => target_num BEGIN
			// 使用 \b 单词边界锚定数字，确保精准匹配（如 GOTO 7 绝不会误伤 GOTO 73），%MATCH1% = GOTO及空格 ，%MATCH2% = 词尾边界
            REPLACE_EVALUATE CASE_INSENSITIVE ~\(\bGOTO[ %TAB%]+\)%target_num%\(\b\)~ BEGIN
                PATCH_PRINT ~%d_filename%数字标签替换GOTO %target_num%->GOTO ia_%BASH_FOR_RES%_%target_num%~
            END ~%MATCH1%ia_%BASH_FOR_RES%_%target_num%%MATCH2%~
        END
		
/*
		// 匹配：IF ~~ 1，等价于IF ~~ THEN BEGIN 1
		REPLACE_TEXTUALLY "~" "ReplaceMe"
		
		REPLACE_EVALUATE CASE_INSENSITIVE ~\([ %TAB%]*IF[ %TAB%]+ReplaceMe[ %TAB%]*ReplaceMe[ %TAB%]*\)\([0-9]+\)\([ %TAB%]*\r?\n?\)~ BEGIN
            SET match_count += 1
        END ~%MATCH1%ia_%BASH_FOR_RES%_%MATCH2%%MATCH3%~
		
		REPLACE_TEXTUALLY "ReplaceMe" "~"

        // +等价于GOTO，匹配：独立的一个加号 + 后面跟着的纯数字目标，示例：+ 24  ->  + ia_%BASH_FOR_RES%_24
        REPLACE_EVALUATE CASE_INSENSITIVE ~\(\+[ %TAB%]+\)\([0-9]+\)\([ %TAB%]*\r?\n?\)~ BEGIN
            SET match_count += 1
        END ~%MATCH1%ia_%BASH_FOR_RES%_%MATCH2%%MATCH3%~
*/	

    BUT_ONLY_IF_IT_CHANGES 

    COPY ~.../ia_d_patch~ ~%BASH_FOR_FILESPEC%~
END
