//铁砧兼容性调整+规则性调整(根据铁砧规则把等级上限从40级扩展到50级，调整的安装文件包括经验、法术位、豁免、命中等，解除铁砧对许愿术出双倍时停高捷的屏蔽)

ACTION_IF (GAME_IS ~eet~) THEN BEGIN

  COPY ~ImprovedAnvil/Setup-ImprovedAnvil.tp2~ ~ImprovedAnvil/Setup-ImprovedAnvil.tp2~
    REPLACE_TEXTUALLY ~bg2ee~ ~bg2ee eet~
  BUT_ONLY

  COPY ~lzbgmod/IATweaksByLZ/resources/creatures/vanilla/imoen10.cre~   ~ImprovedAnvil/resources/creatures/vanilla~      //EET版SOA开局要修改这个，否则卡住，BG2EE则不用 

// 列表
ACTION_DEFINE_ARRAY mod_directory_list BEGIN
    ~ImprovedAnvil/~
	
	~ImprovedAnvil/lib/areas~ ~ImprovedAnvil/lib/core~ ~ImprovedAnvil/lib/creatures~ ~ImprovedAnvil/lib/dialogues~
	~ImprovedAnvil/lib/effects~ ~ImprovedAnvil/lib/items~ ~ImprovedAnvil/lib/kits~ ~ImprovedAnvil/lib/scripts~
	~ImprovedAnvil/lib/spells~ ~ImprovedAnvil/lib/stores~ ~ImprovedAnvil/lib/tpa~
	//~ImprovedAnvil/lib/tables~
	
	~ImprovedAnvil/resources/dlg~ ~ImprovedAnvil/resources/intermediate~
	
	~ImprovedAnvil/scripts/areas~ ~ImprovedAnvil/scripts/beholders~ ~ImprovedAnvil/scripts/clerics~ ~ImprovedAnvil/scripts/common~
	~ImprovedAnvil/scripts/cutscenes~ ~ImprovedAnvil/scripts/demons~ ~ImprovedAnvil/scripts/dragons~
	
	~ImprovedAnvil/scripts/encounters/bridge~ ~ImprovedAnvil/scripts/encounters/brynnlaw~ ~ImprovedAnvil/scripts/encounters/dearnise~ ~ImprovedAnvil/scripts/encounters/docks~
	~ImprovedAnvil/scripts/encounters/druid_grove~ ~ImprovedAnvil/scripts/encounters/druid_quests~ ~ImprovedAnvil/scripts/encounters/firkraag_dungeon~ ~ImprovedAnvil/scripts/encounters/forest_of_myr~
	~ImprovedAnvil/scripts/encounters/forest_of_tethir~ ~ImprovedAnvil/scripts/encounters/graveyard~ ~ImprovedAnvil/scripts/encounters/hell~ ~ImprovedAnvil/scripts/encounters/irenicus_dungeon~
	~ImprovedAnvil/scripts/encounters/oasis~ ~ImprovedAnvil/scripts/encounters/planar_prison~ ~ImprovedAnvil/scripts/encounters/planar_sphere~ ~ImprovedAnvil/scripts/encounters/pocket_plane~
	~ImprovedAnvil/scripts/encounters/random~ ~ImprovedAnvil/scripts/encounters/saradush~ ~ImprovedAnvil/scripts/encounters/sendai_enclave~ ~ImprovedAnvil/scripts/encounters/slums~
	~ImprovedAnvil/scripts/encounters/small_teeth_pass~ ~ImprovedAnvil/scripts/encounters/spellhold~ ~ImprovedAnvil/scripts/encounters/suldanesselar~ ~ImprovedAnvil/scripts/encounters/temple~
	~ImprovedAnvil/scripts/encounters/temple_ruins~ ~ImprovedAnvil/scripts/encounters/the_four~ ~ImprovedAnvil/scripts/encounters/throne_of_bhaal~ ~ImprovedAnvil/scripts/encounters/trademeet~
	~ImprovedAnvil/scripts/encounters/umar_hills~ ~ImprovedAnvil/scripts/encounters/underdark~ ~ImprovedAnvil/scripts/encounters/vagrant_quests~ ~ImprovedAnvil/scripts/encounters/watchers_keep~
	~ImprovedAnvil/scripts/encounters/waukeen_promenade~ ~ImprovedAnvil/scripts/encounters/yaga_shura_keep~
	
	~ImprovedAnvil/scripts/genie~ ~ImprovedAnvil/scripts/golems~ ~ImprovedAnvil/scripts/liches~ ~ImprovedAnvil/scripts/lycanthropes~
	~ImprovedAnvil/scripts/mages~ ~ImprovedAnvil/scripts/misc~ ~ImprovedAnvil/scripts/monsters~ ~ImprovedAnvil/scripts/niether~
	~ImprovedAnvil/scripts/npc~ ~ImprovedAnvil/scripts/patches~ ~ImprovedAnvil/scripts/rakshasa~ ~ImprovedAnvil/scripts/spiders~
	~ImprovedAnvil/scripts/transitions~ ~ImprovedAnvil/scripts/undead~
END

ACTION_DEFINE_ARRAY extension_list BEGIN
    ~baf~
    ~d~
    ~tp2~
    ~tpa~
	~tph~
	~tpp~
END

ACTION_PHP_EACH mod_directory_list AS index1 => mod_dir BEGIN

    //PRINT ~        正在处理的目录: %mod_dir%~

    ACTION_PHP_EACH extension_list AS index2 => ext BEGIN

        // 根据mod_directory_list，进入对应文件夹找后缀extension_list文件
        ACTION_BASH_FOR ~%mod_dir%~ EVALUATE_REGEXP ~^.+\.%ext%$~ BEGIN
            
			// 每个新文件开始时，强制将全局计数器清零，掐断跨文件污染
            OUTER_SET match_count = 0

            //注意：下面这句判断可以去掉，加上是为了使weidu窗口运行时更干净，只显示那些改过的。
            // 匹配任意"CHAPTER"加,
            ACTION_IF FILE_CONTAINS_EVALUATED (~%BASH_FOR_FILESPEC%~ ~"CHAPTER"[ %TAB%]*,~) BEGIN

                // COPY - 纯读入内存，不污染硬盘
                COPY - ~%BASH_FOR_FILESPEC%~ ~.../eet_temp_patch~
		  
                    // 防止IncrementGlobal("CHAPTER",GLOBAL,1)这类被误改
                    REPLACE_TEXTUALLY ~IncrementGlobal~ ~IncrementReplaceMe~
    
                    // 匹配SetGlobal, Global, GlobalGT, GlobalLT, SG, G, GGT, GLT。例： %MATCH1% = Global("CHAPTER","GLOBAL",   %MATCH2% = 2（经过转换后为%eet_chapter%即2+12）   %MATCH3% = )
                    REPLACE_EVALUATE CASE_INSENSITIVE ~\([A-Za-z]*G[A-Za-z]*([ %TAB%]*"CHAPTER"[ %TAB%]*,?[ %TAB%]*"?G?L?O?B?A?L?"?[ %TAB%]*,[ %TAB%]*\)\([0-9]+\)\([ %TAB%]*)\)~ BEGIN
        
		                // 三元运算符 ?   是整数执行MATCH2 + 12，否则不变
                        SET eet_chapter = IS_AN_INT MATCH2 ? (MATCH2 + 12) : MATCH2
        
                        // 仅在真正触发章节转换时，累计匹配次数
                        SET match_count += 1
        
                    END ~%MATCH1%%eet_chapter%%MATCH3%~ 
    
	                // 还原防御改名
                    REPLACE_TEXTUALLY ~IncrementReplaceMe~ ~IncrementGlobal~
					
                BUT_ONLY
				
                // 只有当前文件在内存里确实被改变过，才写入硬盘
                ACTION_IF (match_count > 0) BEGIN
				
                    // 转换成功打印日志
                    PRINT ~    --> 发现文件 (%ext%) 且成功转换 [%match_count% 处] 章节: %BASH_FOR_FILESPEC%~
    
                    // 把内存里改动过的文件写回硬盘
                    COPY ~.../eet_temp_patch~ ~%BASH_FOR_FILESPEC%~
                END
            END
        END
    END
END

END

COPY ~lzbgmod/IATweaksByLZ/lib/core/ids.tph~   ~ImprovedAnvil/lib/core~         //一些规则修改由替换改插入

COPY ~lzbgmod/IATweaksByLZ/lib/core/2da.tph~   ~ImprovedAnvil/lib/core~         //铁砧屏蔽了许愿出双倍时停高捷，修改后解除，下面SPAWNGRP.2DA相关修改调到这里

COPY ~lzbgmod/IATweaksByLZ/lib/areas/05_worldmap.tph~   ~ImprovedAnvil/lib/areas~     //和EEUITweaks、其它MOD图片冲突修复

//已改为改写2da.tph里的相关代码
//和疯神王座、失落女神的呼唤、暗潮涌动、巴洛维亚的血腥骗局冲突修复，铁砧安装方式是直接COPY到override，2da列范围原版BG2EE同原版EET同安装铁砧后的BG2EE或EET，其它MOD需要添加列
//COPY ~lzbgmod/IATweaksByLZ/CRASHFIX/SPAWNGRP.2DA~   ~ImprovedAnvil/resources/2da~
//COPY ~lzbgmod/IATweaksByLZ/CHECK/CLABRN03.2DA~   ~override~      //铁砧是COPY_EXISTING clabrn03.2da加REPLACE_TEXTUALLY，改完后只有40级，所以先COPY到override再让铁砧改


//等级扩展相关
//CDTWEAKS 1(改)
COPY ~lzbgmod/IATweaksByLZ/CDTWEAKSFIX/SKILLRNG.2DA~  ~override~
COPY ~lzbgmod/IATweaksByLZ/CDTWEAKSFIX/SKILLBRD.2DA~  ~override~
COPY ~lzbgmod/IATweaksByLZ/CDTWEAKSFIX/SKILLSHM.2DA~  ~override~

//CDTWEAKS 2
ACTION_CLEAR_ARRAY  cd_extend_tables // use array so we can push HP table entries into it
ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_extend_tables BEGIN
  lvlmodwm => 0 // wild mage level modulation for wild surges
  //monkfist => 0 // monk fist progression
  //mxsplbrd => 0 // bard spell table
  mxspldd  => 0 // dragon disciple spell table
  //mxspldru => 0 // druid spell table
  mxsplpal => 0 // paladin spell table
  //mxsplprs => 0 // priest spell table
  //mxsplran => 0 // ranger spell table
  //mxsplshm => 0 // shaman spell table
  //mxsplsrc => 0 // sorcerer spell table
  //mxsplwiz => 0 // mage spell table
  raisdead => 0 // raise dead temple prices
  splsrckn => 0 // sorcerer spell table
  splshmkn => 0 // shaman spell table

  // manually add hp tables for non-ee games; being added below again harms nothing
  hpbarb   => 0 // barbarian hp table
  hpmonk   => 0 // monk hp table
  hpprs    => 0 // priest hp table
  hprog    => 0 // rogue hp table
  hpwar    => 0 // warrior hp table
  hpwiz    => 0 // mage hp table

END

// add hp tables to list of tables to extend
COPY_EXISTING ~hpclass.2da~ ~override~
  COUNT_2DA_ROWS ~2~ "rows"
  FOR ( index = 1 ; index < rows ; index = index + 1 ) BEGIN
    SET "exists" = 0
    READ_2DA_ENTRY "%index%" 1 2 "table"
    DEFINE_ASSOCIATIVE_ARRAY cd_extend_tables BEGIN "%table%" => 0 END
  END

// easy replacements for 2das with levels as rows
ACTION_PHP_EACH cd_extend_tables AS file => foo BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ THEN BEGIN

    APPEND ~%file%.2da~ ~CD_EOF_CUSTOM~ // also normalizes excessive/missing line breaks at EOF

    // why the chicanery with CD_EOF_CUSTOM and REPLACE_EVALUATE? The 2DA functions get unreliable on two-column tables such as raisdead
    COPY_EXISTING ~%file%.2da~ ~override~ // wild mage level modulation for wild surges
      FOR (index = 1 ; index < 50 ; ++index) BEGIN
        REPLACE_EVALUATE ~^%index%\([ %TAB%].*\)\([%LNL%%MNL%%WNL%]+CD_EOF_CUSTOM\)~ BEGIN
          SET new = index + 1
        END
~%index%\1
%new%\1\2~
      END
      REPLACE_TEXTUALLY ~CD_EOF_CUSTOM~ ~~
      PRETTY_PRINT_2DA
      BUT_ONLY

  END

END

//CDTWEAKS 3
// extend level-based abilities to 50
//ACTION_FOR_EACH file IN backstab crippstr layhands savemonk saveprs saverog savewar savewiz sneakatt thac0 xpbonus wspatck BEGIN
ACTION_FOR_EACH file IN backstab crippstr layhands savemonk saveprs savewar sneakatt BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ THEN BEGIN

    COPY_EXISTING ~%file%.2da~ ~override~
      COUNT_2DA_COLS col_num
      COUNT_2DA_ROWS (col_num - 1) row_num
      READ_2DA_ENTRY 0 (col_num - 2) (col_num - 1) level    // read last enry of top line as level
      READ_2DA_ENTRY 0 0 (col_num - 1) val                  // weidu seems to freak out with a top line w/ one less entry
      SET_2DA_ENTRY  0 0 (col_num - 1) ~CD_DELETE_ME %val%~ // temp
      FOR (index = level ; index < 50 ; ++index) BEGIN
        SET new = index + 1
        FOR (index2 = 1 ; index2 < row_num ; ++index2) BEGIN // extend all other rows with previous column's value
          READ_2DA_ENTRY index2 (col_num - 1) (col_num) val
          SET_2DA_ENTRY  index2 (col_num - 1) (col_num) ~%val% %val%~
        END
        SET_2DA_ENTRY 0 (col_num - 1) (col_num) ~%index% %new%~ // extend level row
        SET col_num += 1
      END
      REPLACE_TEXTUALLY ~CD_DELETE_ME~ ~~
      PRETTY_PRINT_2DA
      BUT_ONLY

  END

END	

//CDTWEAKS 4
ACTION_IF FILE_EXISTS_IN_GAME ~kitlist.2da~ THEN BEGIN // if kits are present

  ACTION_CLEAR_ARRAY  cd_extend_clabs
  ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_extend_clabs BEGIN // start with base class tables
    clabba01 => 0 // generic bard abilities
    clabdr01 => 0 // generic druid abilities
    clabfi01 => 0 // generic fighter abilities
    clabmo01 => 0 // generic monk abilities
    clabpa01 => 0 // generic paladin abilities
    clabpa05 => 0 // fallen paladin abilities
    clabpr01 => 0 // generic priest abilities
    clabrn01 => 0 // generic ranger abilities
    clabrn05 => 0 // fallen ranger abilities
    clabth01 => 0 // generic thief abilities
  END

  // add kit tables dynamically by reading kitlist
  COPY_EXISTING ~kitlist.2da~ ~override~
    COUNT_2DA_ROWS ~9~ "rows"
    FOR ( index = 1 ; index < rows ; index = index + 1 ) BEGIN
      SET "exists" = 0
      READ_2DA_ENTRY "%index%" 5 9 "clab"
      DEFINE_ASSOCIATIVE_ARRAY cd_extend_clabs BEGIN "%clab%" => 0 END
    END
    BUT_ONLY

  // extend clab abilities to 50
  ACTION_PHP_EACH cd_extend_clabs AS file => foo BEGIN

    //ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ THEN BEGIN
	// 只有当文件存在，且名字不属于这四个黑名单文件时，才执行修改
    ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ AND 
              NOT (~%file%~ STR_EQ ~clabdr04~) AND 
              NOT (~%file%~ STR_EQ ~clabfi03~) AND 
              NOT (~%file%~ STR_EQ ~clabmo01~) AND 
              NOT (~%file%~ STR_EQ ~clabth04~) THEN BEGIN

      COPY_EXISTING ~%file%.2da~ ~override~
        // this is adapted from argent77's a7#add_kit_ex#normalize_table to both fix and extend tables
        // https://github.com/Argent77/A7-ImprovedArcher/blob/153f3258f9b884a96ff58537175062bd6b280000/A7%23ImprovedArcher/lib/a7%23add_kit_ex.tpa#L233
        SET num_added = 0
        COUNT_2DA_COLS num_cols
        READ_2DA_ENTRIES_NOW table 1
        READ_2DA_ENTRY_FORMER table 1 0 default
        FOR (row = 0; row < table; ++row) BEGIN
          READ_2DA_ENTRY_FORMER table row 0 line
          FOR (col = 1; col < num_cols && VARIABLE_IS_SET $table(~%row%~ ~%col%~); ++col) BEGIN
            READ_2DA_ENTRY_FORMER table row col v
            TEXT_SPRINT line ~%line% %v%~
          END
          // fill in missing data
          PATCH_IF (row = 2) BEGIN  // header
            FOR (; col < 50; ++col) BEGIN
              SET col_header = col + 1
              TEXT_SPRINT line ~%line% %col_header%~
              SET num_added += 1
            END
          END ELSE PATCH_IF (row > 2) BEGIN // content
            FOR (; col < 51; ++col) BEGIN
              TEXT_SPRINT line ~%line% %default%~
              SET num_added += 1
            END
          END
          TEXT_SPRINT $lines(~%row%~) ~%line%%LNL%~
          SET $lines(~%row%~ ~size~) = STRING_LENGTH $lines(~%row%~)
        END

        // write normalized table to buffer
        PATCH_IF (num_added > 0) BEGIN
          DELETE_BYTES 0 BUFFER_LENGTH
          FOR (row = 0 pos = 0; row < table; ++row) BEGIN
            SET size = $lines(~%row%~ ~size~)
            INSERT_BYTES pos size
            WRITE_ASCIIE pos $lines(~%row%~) (size)
            SET pos += size
          END

          // attempt to populate newly extended table with meaningful entries
          PATCH_IF num_cols > 37 BEGIN // don't bother unless we're already at 40-ish columns
            COUNT_2DA_ROWS (num_cols - 1) num_rows
            FOR (col = num_cols ; col < 51 ; ++col) BEGIN
              SET entries = 0
              CLEAR_ARRAY cd_add_abilities
              SET ref_col = col - 8
              FOR (row = 0 ; row < num_rows ; ++row) BEGIN // loop of per-8-levels (leave 4 for last loop)
                READ_2DA_ENTRY row ref_col num_cols entry
                PATCH_IF (("%entry%" STRING_COMPARE_REGEXP "^[0-9]+$") AND ( // safety check to make sure we don't grab the header row
                         ("%entry%" STRING_COMPARE_CASE "AP_OHRBEAR6" = 0)
                )) BEGIN
                  PATCH_IF entries <= num_rows BEGIN
                    SET entries += 1
                    DEFINE_ASSOCIATIVE_ARRAY cd_add_abilities BEGIN ~%entry%~, ~%entries%~ => 0 END
                  END ELSE BEGIN
                    SET row = num_rows // kill loop
                  END
                END
              END
              SET ref_col = col - 10
              FOR (row = 0 ; row < num_rows ; ++row) BEGIN // loop of per-10-levels (also catches per 5)
                READ_2DA_ENTRY row ref_col num_cols entry
                PATCH_IF (("%entry%" STRING_COMPARE_REGEXP "^[0-9]+$") AND ( // safety check to make sure we don't grab the header row
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL122" = 0) OR  // +1 missile to-hit, damage (clabrn02)
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL441" = 0) OR  // +1 AC (clabth04)
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL813" = 0) OR  // +1 movement speed (clabmo01, clabmo02, clabmo03)
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL822" = 0) OR  // base AC (clabmo01, clabmo02, clabmo03)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTMPS1" = 0) OR  // holy power (ohtempus)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTMPS2" = 0) OR  // chaos of battle (ohtempus)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTYR1" = 0) OR   // exaltation (ohtyr)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTYR2" = 0) OR   // divine favor (ohtyr)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL412" = 0) OR  // set snare (clabth01, clabth02, clabth03, clabth04)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL414" = 0) OR  // set special snare (clabth03)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL621" = 0) OR  // summon spirit animal (clabdr02)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL721" = 0) OR  // storm shield (clabpr02)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL722" = 0) OR  // lightning bolt (clabpr02)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL731" = 0) OR  // seeking sword (clabpr03)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL732" = 0) OR  // true sight (clabpr03)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL741" = 0) OR  // boon of lathander (clabpr04)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL742" = 0) OR  // hold undead (clabpr04)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPSD02" = 0) OR   // shadowstep (clabth05)
                         (("%entry%" STRING_COMPARE_CASE "AP_SPCL141" = 0) AND ("%SOURCE_RES%" STRING_COMPARE_CASE "clabth04" = 0)) OR // +1 to-hit, damage (clabfi04, clabth04)
                         (("%entry%" STRING_COMPARE_CASE "GA_SPCL423" = 0) AND ("%SOURCE_RES%" STRING_COMPARE_CASE "clabpa06" = 0))    // poison weapon (clabpa06, clabth02)
                )) BEGIN
                  PATCH_IF entries <= num_rows BEGIN
                    SET entries += 1
                    DEFINE_ASSOCIATIVE_ARRAY cd_add_abilities BEGIN ~%entry%~, ~%entries%~ => 0 END
                  END ELSE BEGIN
                    SET row = num_rows // kill loop
                  END
                END
              END
              SET ref_col = col - 12
              FOR (row = 0 ; row < num_rows ; ++row) BEGIN // loop of per-10-levels (also catches per 5)
                READ_2DA_ENTRY row ref_col num_cols entry
                PATCH_IF (("%entry%" STRING_COMPARE_REGEXP "^[0-9]+$") AND NOT ( // safety check to make sure we don't grab the header rowNOT (
                          ("%entry%" STRING_COMPARE_CASE "****" = 0) OR        // blank entry
                          ("%entry%" STRING_COMPARE_CASE "AP_OHRBEAR6" = 0) OR // regen, AC
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL122" = 0) OR  // +1 missile to-hit, damage (clabrn02)
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL441" = 0) OR  // +1 AC (clabth04)
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL813" = 0) OR  // +1 movement speed (clabmo01, clabmo02, clabmo03)
                          ("%entry%" STRING_COMPARE_CASE "AP_SPCL822" = 0) OR  // base AC (clabmo01, clabmo02, clabmo03)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTMPS1" = 0) OR  // holy power (ohtempus)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTMPS2" = 0) OR  // chaos of battle (ohtempus)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTYR1" = 0) OR   // exaltation (ohtyr)
                          ("%entry%" STRING_COMPARE_CASE "GA_OHTYR2" = 0) OR   // divine favor (ohtyr)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL412" = 0) OR  // set snare (clabth01, clabth02, clabth03, clabth04)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL414" = 0) OR  // set special snare (clabth03)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL621" = 0) OR  // summon spirit animal (clabdr02)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL721" = 0) OR  // storm shield (clabpr02)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL722" = 0) OR  // lightning bolt (clabpr02)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL731" = 0) OR  // seeking sword (clabpr03)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL732" = 0) OR  // true sight (clabpr03)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL741" = 0) OR  // boon of lathander (clabpr04)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPCL742" = 0) OR  // hold undead (clabpr04)
                          ("%entry%" STRING_COMPARE_CASE "GA_SPSD02" = 0) OR   // shadowstep (clabth05)
                         (("%entry%" STRING_COMPARE_CASE "AP_SPCL141" = 0) AND ("%SOURCE_RES%" STRING_COMPARE_CASE "clabth04" = 0)) OR // +1 to-hit, damage (clabfi04, clabth04)
                         (("%entry%" STRING_COMPARE_CASE "GA_SPCL423" = 0) AND ("%SOURCE_RES%" STRING_COMPARE_CASE "clabpa06" = 0))    // poison weapon (clabpa06, clabth02)
                )) BEGIN
                  PATCH_IF entries <= num_rows BEGIN
                    SET entries += 1
                    DEFINE_ASSOCIATIVE_ARRAY cd_add_abilities BEGIN ~%entry%~, ~%entries%~ => 0 END
                  END ELSE BEGIN
                    SET row = num_rows // kill loop
                  END
                END
              END
              PATCH_IF entries > 0 BEGIN
                PATCH_PHP_EACH cd_add_abilities AS params => foo BEGIN
                  PATCH_IF params_1 <= num_rows BEGIN
                    SET_2DA_ENTRY params_1 col num_cols ~%params_0%~
                  END
                END
              END
            END // end column loop
          END // end routine to add populate table extension
          PRETTY_PRINT_2DA
        END
        BUT_ONLY

    END

  END

END

/*
//CDTWEAKS 5(改)
COPY_EXISTING ~XPCAP.2DA~ ~override~
    REPLACE_TEXTUALLY ~\([A-Za-z_]+[ %tab%]+\)\([0-9]+\)[ %tab%]*~ ~\1-1~
BUT_ONLY
*/

//CDTWEAKS 6(改)
ACTION_CLEAR_ARRAY  cd_start_areas

ACTION_DEFINE_ASSOCIATIVE_ARRAY cd_start_areas BEGIN
    //startare => 0
    startbp  => 0
END

ACTION_IF FILE_EXISTS_IN_GAME ~campaign.2da~ THEN BEGIN

    COPY_EXISTING ~campaign.2da~ ~override~
        COUNT_2DA_COLS col_num
        COUNT_2DA_ROWS (col_num - 1) row_num
			FOR (index = 1 ; index < row_num ; ++index) BEGIN // start at 1 to skip header row
				READ_2DA_ENTRY index 13 13 file
				DEFINE_ASSOCIATIVE_ARRAY cd_start_areas BEGIN "%file%" => 0 END
			END
    BUT_ONLY
END

// for EE
ACTION_PHP_EACH cd_start_areas AS file => val BEGIN

    //PRINT ~patching campaign file %file%.2da~

    //ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ THEN BEGIN
	// 加上黑名单过滤，如果是 startare 则直接跳过不显示、不修改
    ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ AND NOT (~%file%~ STR_EQ ~startare~) THEN BEGIN

        PRINT ~patching campaign file %file%.2da~

		COPY_EXISTING ~%file%.2da~ ~override~ 
			REPLACE_TEXTUALLY ~\(START_\(MP_\)?XP_CAP[ %tab%]+\)\([0-9]+\)[ %tab%]*~ ~\1-1~
			//写法2
			//REPLACE_TEXTUALLY ~\(START_\(MP_\)?XP_CAP[ %tab%]+\)[^0-9-]*\([0-9]+\)[ %tab%]*~ ~\1-1~
        BUT_ONLY
    END
END


//CLABRN03.2DA    hpclass.2da
//EET安装去经验上限一共改动84个2da，再安装铁砧又会对84个2da中的22个重新改动、外加新增4个2da(clabma03.2da/CLABMO02.2DA/CLABMO03.2DA/CLABSH01.2DA)，也就是有62个2da铁砧不会改动、需要借助去经验上限修改。
//实际安装借用CDTWEAKS时，不需要借用去经验上限的xplevel.2da，需要补充没有的SKILLSHM.2DA，实际改动也是84个2da，后面安装IA遇到相同2da会自动覆盖。
//IATweaksByLZ/resources/2da里除clabma03.2da、CLABMO02.2DA、CLABMO03.2DA、CLABSH01.2DA、XPLEVEL.2DA这5个以外的19个2da，需要在上面扩展代码中排除，防止2次操作同一个文件导致卸载时报错。



//IA
COPY ~lzbgmod/IATweaksByLZ/IAKITS/VAGRAN.2DA~    ~ImprovedAnvil/resources/2da~
COPY ~lzbgmod/IATweaksByLZ/IAKITS/AMDK.2DA~      ~ImprovedAnvil/resources/2da~
COPY ~lzbgmod/IATweaksByLZ/IAKITS/RBK.2DA~       ~ImprovedAnvil/resources/2da~
COPY ~lzbgmod/IATweaksByLZ/IAKITS/PROTEC.2DA~    ~ImprovedAnvil/resources/2da~
COPY ~lzbgmod/IATweaksByLZ/IAKITS/ARVOREEN.2DA~  ~ImprovedAnvil/resources/2da~

COPY ~lzbgmod/IATweaksByLZ/resources/2da~   ~ImprovedAnvil/resources/2da~       //根据铁砧规则把等级扩展到50级，每级经验、法术位、豁免、命中等