IF
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("OHBOSSARest","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("OHBOSSARest","LOCALS",FOUR_HOURS)
		SetGlobal("Prepare","LOCALS",0)
		SetGlobal("Iadra11","LOCALS",0)
		SetGlobal("Iainterrupt","LOCALS",0)
		SetGlobal("Prepare2","LOCALS",0)
		SetGlobal("Iadra08","LOCALS",0)
		SetGlobal("Iaabs","LOCALS",0)
		SetGlobal("Iahardiness","LOCALS",0)
		SetGlobal("Irefreshsi","LOCALS",0)
		SetGlobal("Iareversal","LOCALS",0)
		SetGlobal("Iacastbreach","LOCALS",0)
		SetGlobal("Iaremove","LOCALS",0)
		SetGlobal("Iadispelpotp1","LOCALS",0)
		SetGlobal("Iadispelpot","LOCALS",0)
		SetGlobal("Iadra12","LOCALS",0)
		SetGlobal("Iadra03","LOCALS",0)
		SetGlobal("Summon","LOCALS",0)
		SetGlobal("Iacshla","LOCALS",0)
		SetGlobal("Iagwhla","LOCALS",0)
		SetGlobal("Ianoward","LOCALS",0)
		SetGlobal("Iadra04","LOCALS",0)
		SetGlobal("Iawilting","LOCALS",0)
		SetGlobal("Iadra07","LOCALS",0)
		SetGlobal("Iamissile","LOCALS",0)
		SetGlobal("Iacometbreath","LOCALS",0)
		SetGlobal("Iafinger","LOCALS",0)
		SetGlobal("Iafarrow","LOCALS",0)
		SetGlobal("OHBATrapNum","LOCALS",0)
		SetGlobal("OHBAFirstTSCombo","LOCALS",0)
		SetGlobal("OHBOSSWishNum","LOCALS",0)
		SetGlobal("FirstWishDTS","LOCALS",0)
		SetGlobal("AfterRestDTS","LOCALS",0)
		ReallyForceSpellRES("SPWII07",Myself)  // No such index
		Rest()
END

IF
	OR(2)
		Allegiance(Myself,ENEMY)
		Range([GOODCUTOFF],75)
	Global("Prepare","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prepare","LOCALS",1)
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (火焰护盾（红）)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)  // SPWI606.SPL (防护魔法能量)
		ReallyForceSpellRES("jwglobe",Myself)  // 法术无效结界
		ReallyForceSpellRES("spwi613",Myself)  // 高等加速术
		ReallyForceSpellRES("spwii03",Myself)  // 法术反转
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (法术免疫：防护系)
END

IF
	Global("Iapcastts","GLOBAL",1)
	Global("Iatsinvulner","LOCALS",0)
	!HPLT(Myself,2)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",1)
		ApplySpellRES("SPINI70",Myself)  // No such index
END

IF
	Global("Iapcastts","GLOBAL",0)
	Global("Iatsinvulner","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iatsinvulner","LOCALS",0)
		ApplySpellRES("SPINI71",Myself)  // No such index
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	OR(2)
		CheckStatGT(Myself,0,SCRIPTINGSTATE9)
		Global("Iapcastts","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
END

IF
	OR(5)
		See([NEUTRAL])
		See([ALLY])
		See([FAMILIAR])
		See([CONTROLLED])
		See([CHARMED])
	InWeaponRange(LastSeenBy(Myself))
	TookDamage()
	!InWeaponRange(LastHitter(Myself))
	WeaponEffectiveVs(LastHitter(Myself),MAINHAND)
	WeaponCanDamage(LastHitter(Myself),MAINHAND)
THEN
	RESPONSE #100
		ReallyForceSpell(LastHitter(Myself),WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (任意门)
		AttackOneRound(LastHitter(Myself))
END

IF
	OR(2)
		!Detect([PC])
		!Detect([GOODCUTOFF])
	ActionListEmpty()
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	CheckStatLT(Player1,1,SANCTUARY)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!StateCheck(Player1,STATE_NOT_APPROACHABLE)
	!GlobalTimerNotExpired("MO_TeleToPlayer","LOCALS")
THEN
	RESPONSE #100
		MoveToObject(Player1)
	RESPONSE #100
		SetGlobalTimer("MO_TeleToPlayer","LOCALS",ONE_ROUND)
		ReallyForceSpell(Player1,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (任意门)
		Continue()
END

IF
	OR(2)
		!Detect([PC])
		!Detect([GOODCUTOFF])
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
	OR(3)
		CheckStatGT(Player1,0,SANCTUARY)
		StateCheck(Player1,STATE_REALLY_DEAD)
		StateCheck(Player1,STATE_NOT_APPROACHABLE)
	!GlobalTimerNotExpired("MO_TeleToPlayer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("MO_TeleToPlayer","LOCALS",ONE_ROUND)
		ReallyForceSpell(Player2,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (任意门)
		Continue()
	RESPONSE #100
		SetGlobalTimer("MO_TeleToPlayer","LOCALS",ONE_ROUND)
		ReallyForceSpell(Player3,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (任意门)
		Continue()
	RESPONSE #100
		SetGlobalTimer("MO_TeleToPlayer","LOCALS",ONE_ROUND)
		ReallyForceSpell(Player4,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (任意门)
		Continue()
	RESPONSE #100
		SetGlobalTimer("MO_TeleToPlayer","LOCALS",ONE_ROUND)
		ReallyForceSpell(Player5,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (任意门)
		Continue()
	RESPONSE #100
		SetGlobalTimer("MO_TeleToPlayer","LOCALS",ONE_ROUND)
		ReallyForceSpell(Player6,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (任意门)
		Continue()
END

IF
	OR(4)
		StateCheck(Myself,STATE_SLEEPING)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_BLIND)
		!CheckStat(Myself,0,POLYMORPHED)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_TRUE_DISPEL_MAGIC)  // SPWI326.SPL (解除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	OR(4)
		SpellCastPriest([ANYONE],CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (封魔术)
		SpellCastPriest([ANYONE],CLERIC_SUMMON_INSECTS)  // SPPR319.SPL (召唤昆虫)
		SpellCastPriest([ANYONE],CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (疫病虫群)
		SpellCastPriest([ANYONE],CLERIC_CREEPING_DOOM)  // SPPR717.SPL (漫天虫蚀)
	CheckStatGT(Myself,49,SPELLFAILUREMAGE)
	CheckStat(Myself,1,SCRIPTINGSTATE9)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_TRUE_DISPEL_MAGIC)  // SPWI326.SPL (解除魔法)
END

IF
	SpellCastPriest(Player1,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player1)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player1,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player2,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player2)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player2,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player3,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player3)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player3,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player4,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player4)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player4,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player5,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player5)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player5,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player6,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player6)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player6,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	GlobalLT("OHBATrapNum","LOCALS",15)
	!GlobalTimerNotExpired("OHBAIATrapCombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	Allegiance(Myself,ENEMY)
	See([PC])
	!HPLT(LastSeenBy(Myself),50)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	ActionListEmpty()
	RandomNum(10,1)
THEN
	RESPONSE #100
		SetGlobalTimer("OHBAIATrapCombo","LOCALS",FOUR_ROUNDS)
		ForceSpell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (高等迅捷)
END

IF
	GlobalLT("OHBATrapNum","LOCALS",15)
	!GlobalTimerNotExpired("OHBAIATrapCombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!HPLT(LastSeenBy(Myself),50)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	ActionListEmpty()
	RandomNum(10,2)
THEN
	RESPONSE #100
		SetGlobalTimer("OHBAIATrapCombo","LOCALS",FOUR_ROUNDS)
		ForceSpell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (高等迅捷)
END

IF
	GlobalLT("OHBATrapNum","LOCALS",15)
	!GlobalTimerNotExpired("OHBAIATrapCombo","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!HPLT(LastSeenBy(Myself),50)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	ActionListEmpty()
	RandomNum(10,3)
THEN
	RESPONSE #100
		SetGlobalTimer("OHBAIATrapCombo","LOCALS",FOUR_ROUNDS)
		ForceSpell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (高等迅捷)
END

IF
	GlobalLT("OHBATrapNum","LOCALS",15)
	CheckStatGT(Myself,0,AURACLEANSING)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	Allegiance(Myself,ENEMY)
	See([PC])
	!HPLT(LastSeenBy(Myself),50)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	RandomNum(3,1)
THEN
	RESPONSE #50
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",LastSeenBy(Myself))  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		IncrementGlobal("OHBATrapNum","LOCALS",3)
		SetInterrupt(TRUE)
	RESPONSE #50
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",LastSeenBy(Myself))  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		IncrementGlobal("OHBATrapNum","LOCALS",3)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	GlobalLT("OHBATrapNum","LOCALS",15)
	CheckStatGT(Myself,0,AURACLEANSING)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	Allegiance(Myself,ENEMY)
	See(SecondNearest([PC]))
	!HPLT(LastSeenBy(Myself),50)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	RandomNum(3,2)
THEN
	RESPONSE #50
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",LastSeenBy(Myself))  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		IncrementGlobal("OHBATrapNum","LOCALS",3)
		SetInterrupt(TRUE)
	RESPONSE #50
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",LastSeenBy(Myself))  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		IncrementGlobal("OHBATrapNum","LOCALS",3)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	GlobalLT("OHBATrapNum","LOCALS",15)
	CheckStatGT(Myself,0,AURACLEANSING)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	Allegiance(Myself,ENEMY)
	See(ThirdNearest([PC]))
	!HPLT(LastSeenBy(Myself),50)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	RandomNum(3,3)
THEN
	RESPONSE #50
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",LastSeenBy(Myself))  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		IncrementGlobal("OHBATrapNum","LOCALS",3)
		SetInterrupt(TRUE)
	RESPONSE #50
		SetInterrupt(FALSE)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",LastSeenBy(Myself))  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		IncrementGlobal("OHBATrapNum","LOCALS",3)
		AttackOneRound(LastSeenBy(Myself))
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,ENEMY)
	SpellCast([ANYONE],WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
	!GlobalTimerNotExpired("TSNOCUT","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("TSNOCUT","LOCALS",THREE_ROUNDS)
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	Global("OHBOSSAGetDTS","LOCALS",1)
	!GlobalTimerNotExpired("DTSNOCUT","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("OHBOSSAGetDTS","LOCALS",0)
		Continue()
END

IF
	Global("OHBAFirstTSCombo","LOCALS",0)
	!GlobalTimerNotExpired("BOSSAWISHDEALY","LOCALS")
	!GlobalTimerNotExpired("TSNOCUT","LOCALS")
	!GlobalTimerNotExpired("DTSNOCUT","LOCALS")
	ActionListEmpty()
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
THEN
	RESPONSE #100
		SetGlobal("OHBAFirstTSCombo","LOCALS",1)
		SetGlobalTimer("BOSSAWISHDEALY","LOCALS",SEVEN_ROUNDS)
		SetInterrupt(FALSE)
		MoveToObject(LastSeenBy(Myself))
		ForceSpell(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
		ForceSpell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (高等迅捷)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		MoveToObject(SecondNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(ThirdNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		MoveToObject(FourthNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(Player1)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		SetInterrupt(TRUE)
END

IF
	GlobalLT("OHBOSSWishNum","LOCALS",3)
	Global("OHBOSSWish","LOCALS",0)
	TriggerOverride("OHBOSSB",Global("OHBOSSWish","LOCALS",0))
	!TriggerOverride("OHBOSSB",GlobalTimerNotExpired("BOSSABWISHDEALY","LOCALS"))
	!GlobalTimerNotExpired("BOSSABWISHDEALY","LOCALS")
	!GlobalTimerNotExpired("BOSSAWISHDEALY","LOCALS")
	!GlobalTimerNotExpired("TSNOCUT","LOCALS")
	!GlobalTimerNotExpired("DTSNOCUT","LOCALS")
	ActionListEmpty()
	See([PC])
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	NumCreatureLT("OHBBWISH",1)  // 贵族风巨灵
	RandomNum(2,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("OHBOSSWishNum","LOCALS",1)
		SetGlobal("OHBOSSWish","LOCALS",1)
		SetGlobalTimer("BOSSABWISHDEALY","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("BOSSAWISHDEALY","LOCALS",SEVEN_ROUNDS)
		ClearAllActions()
		StartCutSceneMode()
		StartCutScene("OHBBCUTA")
		SetInterrupt(TRUE)
END

IF
	Global("FirstWishDTS","LOCALS",0)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("FirstWishDTS","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		SetInterrupt(TRUE)
END

IF
	Global("FirstWishDTS","LOCALS",0)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("FirstWishDTS","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		SetInterrupt(TRUE)
END

IF
	Global("FirstWishDTS","LOCALS",0)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("FirstWishDTS","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		SetInterrupt(TRUE)
END

IF
	Global("FirstWishDTS","LOCALS",0)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("FirstWishDTS","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		SetInterrupt(TRUE)
END

IF
	Global("FirstWishDTS","LOCALS",0)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("FirstWishDTS","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		SetInterrupt(TRUE)
END

IF
	Global("FirstWishDTS","LOCALS",0)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasBounceEffects(LastSeenBy(Myself))
THEN
	RESPONSE #100
		SetGlobal("FirstWishDTS","LOCALS",1)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
		SetInterrupt(TRUE)
END

IF
	Global("AfterRestDTS","LOCALS",1)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("AfterRestDTS","LOCALS",0)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		MoveToObject(SecondNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(ThirdNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		MoveToObject(FourthNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(Player1)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		SetInterrupt(TRUE)
END

IF
	Global("AfterRestDTS","LOCALS",1)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("AfterRestDTS","LOCALS",0)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		MoveToObject(SecondNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(ThirdNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		MoveToObject(FourthNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(Player1)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		SetInterrupt(TRUE)
END

IF
	Global("AfterRestDTS","LOCALS",1)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("AfterRestDTS","LOCALS",0)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		MoveToObject(SecondNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(ThirdNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		MoveToObject(FourthNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(Player1)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		SetInterrupt(TRUE)
END

IF
	Global("AfterRestDTS","LOCALS",1)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("AfterRestDTS","LOCALS",0)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		MoveToObject(SecondNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(ThirdNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		MoveToObject(FourthNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(Player1)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		SetInterrupt(TRUE)
END

IF
	Global("AfterRestDTS","LOCALS",1)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("AfterRestDTS","LOCALS",0)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		MoveToObject(SecondNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(ThirdNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		MoveToObject(FourthNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(Player1)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		SetInterrupt(TRUE)
END

IF
	Global("AfterRestDTS","LOCALS",1)
	Global("OHBOSSAGetDTS","LOCALS",1)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("AfterRestDTS","LOCALS",0)
		SetInterrupt(FALSE)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_STUN)  // SPWI816.SPL (震慑法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_FEAR)  // SPWI811.SPL (恐惧法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_SYMBOL_DEATH)  // SPWI817.SPL (死亡法印)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)  // SPWI615.SPL (连环闪电)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_LIGHTNING_BOLT)  // SPWI308.SPL (闪电术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpellRange(LastSeenBy(Myself),WIZARD_FIREBALL)  // SPWI304.SPL (火球术)
		ForceSpell(Myself,WIZARD_BLINDNESS)  // SPWI106.SPL (目盲)
		ForceSpell(Myself,WIZARD_IMPROVED_HASTE)  // SPWI613.SPL (高等加速术)
		ForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (高等隐形术)
		MoveToObject(LastSeenBy(Myself))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",LastSeenBy(Myself))  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",LastSeenBy(Myself))  // No such index
		MoveToObject(SecondNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(ThirdNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		MoveToObject(FourthNearest([PC]))
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,THIEF_SET_SNARE)  // SPCL412.SPL (装设陷阱)
		ForceSpellRangeRES("SPCL411",[PC])  // No such index
		MoveToObject(Player1)
		ReallyForceSpell(Myself,ROGUE_SET_SPIKE_TRAP)  // SPCL910.SPL (装设尖刺陷阱)
		ForceSpellRangeRES("SPCL910B",[PC])  // No such index
		ReallyForceSpell(Myself,ROGUE_SET_EXPLODING_TRAP)  // SPCL911.SPL (装设爆裂陷阱)
		ForceSpellRangeRES("SPCL911B",[PC])  // No such index
		ForceSpell(Myself,CLERIC_CURE_DISEASE)  // SPPR317.SPL (治疗疾病)
		SetInterrupt(TRUE)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		SpellCast(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
		Global("OHBOSSAGetDTS","LOCALS",1)
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
	WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		SpellCast(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
		Global("OHBOSSAGetDTS","LOCALS",1)
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
	WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		SpellCast(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
		Global("OHBOSSAGetDTS","LOCALS",1)
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
	WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		SpellCast(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
		Global("OHBOSSAGetDTS","LOCALS",1)
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
	WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		SpellCast(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
		Global("OHBOSSAGetDTS","LOCALS",1)
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
	WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		SpellCast(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
		Global("OHBOSSAGetDTS","LOCALS",1)
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStat(LastSeenBy(Myself),0,SANCTUARY)
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
	WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("POTN34",Myself)  // 魔法防护药水
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	CheckStatLT(Myself,40,RESISTMAGIC)
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		UseItem("POTN34",Myself)  // 魔法防护药水
		DisplayStringHead(Myself,46150)  // 喝下药水
END

IF
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,80)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	HasItem("POTN55",Myself)  // 超级强效医疗药水
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // 喝下药水
		UseItem("POTN55",Myself)  // 超级强效医疗药水
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",0)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player1,0,SCRIPTINGSTATE7)
		CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player2,0,SCRIPTINGSTATE7)
		CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player3,0,SCRIPTINGSTATE7)
		CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player4,0,SCRIPTINGSTATE7)
		CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player5,0,SCRIPTINGSTATE7)
		CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",1)
	OR(2)
		CheckStatGT(Player6,0,SCRIPTINGSTATE7)
		CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	CheckStatLT(Player1,25,RESISTMAGIC)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player1)
	Global("Iap1nr","GLOBAL",2)
	CheckStatGT(Player1,0,SCRIPTINGSTATE7)
	CheckStatGT(Player1,0,MINORGLOBE)
	HPLT(Player1,60)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	CheckStatLT(Player2,25,RESISTMAGIC)
	HPLT(Player2,60)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player2)
	Global("Iap2nr","GLOBAL",2)
	CheckStatGT(Player2,0,SCRIPTINGSTATE7)
	CheckStatGT(Player2,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	CheckStatLT(Player3,25,RESISTMAGIC)
	HPLT(Player3,60)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player3)
	Global("Iap3nr","GLOBAL",2)
	CheckStatGT(Player3,0,SCRIPTINGSTATE7)
	CheckStatGT(Player3,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	CheckStatLT(Player4,25,RESISTMAGIC)
	HPLT(Player4,60)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player4)
	Global("Iap4nr","GLOBAL",2)
	CheckStatGT(Player4,0,SCRIPTINGSTATE7)
	CheckStatGT(Player4,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	CheckStatLT(Player5,25,RESISTMAGIC)
	HPLT(Player5,60)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player5)
	Global("Iap5nr","GLOBAL",2)
	CheckStatGT(Player5,0,SCRIPTINGSTATE7)
	CheckStatGT(Player5,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	!HPLT(Myself,2)
	GlobalLT("Iadra11","LOCALS",4)
	Allegiance(Myself,ENEMY)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	CheckStatLT(Player6,25,RESISTMAGIC)
	HPLT(Player6,60)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!HasBounceEffects(Player6)
	Global("Iap6nr","GLOBAL",2)
	CheckStatGT(Player6,0,SCRIPTINGSTATE7)
	CheckStatGT(Player6,0,MINORGLOBE)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra11","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE20)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // 拉络克打断术
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE20)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // 拉络克打断术
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(ThirdNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE20)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // 拉络克打断术
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(FourthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE20)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // 拉络克打断术
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(FifthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE20)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // 拉络克打断术
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(SixthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE9)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,AURACLEANSING)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE20)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	Global("Iainterrupt","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iainterrupt","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDecRES("SPWI511",LastSeenBy(Myself))  // 拉络克打断术
END

IF
	Allegiance(Myself,ENEMY)
	ActionListEmpty()
	!HPLT(Myself,2)
	HPPercentLT(Myself,75)
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // 波塞东的愤怒+5
	Global("Prepare2","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Prepare2","LOCALS",1)
		DisplayString(Myself,26328)  // 连锁意外术
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	GlobalLT("Iadra08","LOCALS",8)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iadra08","LOCALS",1)
		SpellNoDec(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Allegiance(Myself,ENEMY)
	AttackedBy([GOODCUTOFF],DEFAULT)
	TookDamage()
	CheckStat(Myself,0,SCRIPTINGSTATE6)
	GlobalLT("Iaabs","LOCALS",9)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iaabs","LOCALS",1)
		SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	GlobalLT("Iahardiness","LOCALS",9)
	HPPercentLT(Myself,90)
	CheckStatLT(Myself,90,RESISTSLASHING)
	CheckStatLT(Myself,90,RESISTCRUSHING)
	CheckStatLT(Myself,90,RESISTPIERCING)
	AttackedBy([GOODCUTOFF],DEFAULT)
	TookDamage()
THEN
	RESPONSE #100
		IncrementGlobal("Iahardiness","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (强韧)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatGT(Myself,0,SCRIPTINGSTATE6)
	CheckStat(Myself,0,SCRIPTINGSTATE7)
	Global("Irefreshsi","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobal("Irefreshsi","LOCALS",1)
		SpellNoDec(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (法术免疫：防护系)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",ONE_TURN)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (真实视域)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",ONE_TURN)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (真实视域)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!GlobalTimerNotExpired("truesight","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",ONE_TURN)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (真实视域)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See([PC])
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(SecondNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaexrm","LOCALS")
	See(ThirdNearest([PC]))
	OR(3)
		StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaexrm","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	Detect([PC])
	OR(2)
		!See([PC])
		!See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",ONE_TURN)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (真实视域)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // 法术重击
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	Global("Iaspellstrike","OHSSAB",0)
	GlobalGT("Iap1nr","GLOBAL",1)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","OHSSAB",1)
		SetGlobal("Iap1nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // 使用卷轴
		UseItem("scrl9m",Player1)  // 法术重击
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	GlobalGT("Iap1nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap1nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	Global("Iap1nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	OR(2)
		CheckStatGT(Player1,2,SCRIPTINGSTATE6)
		CheckStat(Player1,1,SCRIPTINGSTATE11)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap1nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player1,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // 法术重击
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	Global("Iaspellstrike","OHSSAB",0)
	GlobalGT("Iap2nr","GLOBAL",1)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","OHSSAB",1)
		SetGlobal("Iap2nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // 使用卷轴
		UseItem("scrl9m",Player2)  // 法术重击
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	GlobalGT("Iap2nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap2nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	Global("Iap2nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	!CheckStat(Player2,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	OR(2)
		CheckStatGT(Player2,2,SCRIPTINGSTATE6)
		CheckStat(Player2,1,SCRIPTINGSTATE11)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap2nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player2,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // 法术重击
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	Global("Iaspellstrike","OHSSAB",0)
	GlobalGT("Iap3nr","GLOBAL",1)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","OHSSAB",1)
		SetGlobal("Iap3nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // 使用卷轴
		UseItem("scrl9m",Player3)  // 法术重击
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	GlobalGT("Iap3nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap3nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	Global("Iap3nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	!CheckStat(Player3,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	OR(2)
		CheckStatGT(Player3,2,SCRIPTINGSTATE6)
		CheckStat(Player3,1,SCRIPTINGSTATE11)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap3nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player3,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // 法术重击
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	Global("Iaspellstrike","OHSSAB",0)
	GlobalGT("Iap4nr","GLOBAL",1)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","OHSSAB",1)
		SetGlobal("Iap4nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // 使用卷轴
		UseItem("scrl9m",Player4)  // 法术重击
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	GlobalGT("Iap4nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap4nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	Global("Iap4nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	!CheckStat(Player4,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	OR(2)
		CheckStatGT(Player4,2,SCRIPTINGSTATE6)
		CheckStat(Player4,1,SCRIPTINGSTATE11)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap4nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player4,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // 法术重击
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	Global("Iaspellstrike","OHSSAB",0)
	GlobalGT("Iap5nr","GLOBAL",1)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","OHSSAB",1)
		SetGlobal("Iap5nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // 使用卷轴
		UseItem("scrl9m",Player5)  // 法术重击
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	GlobalGT("Iap5nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap5nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	Global("Iap5nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	!CheckStat(Player5,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	OR(2)
		CheckStatGT(Player5,2,SCRIPTINGSTATE6)
		CheckStat(Player5,1,SCRIPTINGSTATE11)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap5nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player5,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("scrl9m",Myself)  // 法术重击
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	Global("Iaspellstrike","OHSSAB",0)
	GlobalGT("Iap6nr","GLOBAL",1)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iaspellstrike","OHSSAB",1)
		SetGlobal("Iap6nr","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46153)  // 使用卷轴
		UseItem("scrl9m",Player6)  // 法术重击
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	GlobalGT("Iap6nr","GLOBAL",0)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		IncrementGlobal("Iap6nr","GLOBAL",-1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	Global("Iap6nb","GLOBAL",1)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("Iafmbreach","LOCALS")
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	!CheckStat(Player6,1,SCRIPTINGSTATE7)
	!CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
	GlobalLT("Iacastbreach","LOCALS",9)
	OR(2)
		CheckStatGT(Player6,2,SCRIPTINGSTATE6)
		CheckStat(Player6,1,SCRIPTINGSTATE11)
THEN
	RESPONSE #100
		IncrementGlobal("Iacastbreach","LOCALS",1)
		SetGlobal("Iap6nb","GLOBAL",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SetGlobalTimer("Iafmbreach","LOCALS",TWO_ROUNDS)
		SpellNoDec(Player6,WIZARD_BREACH)  // SPWI513.SPL (破解术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(Player1)
	!CheckStat(Player1,1,SCRIPTINGSTATE7)
	OR(2)
		CheckStat(Player1,2,SCRIPTINGSTATE3)
		CheckStat(Player1,1,SCRIPTINGSTATE15)
	!StateCheck(Player1,STATE_STUNNED)
	!StateCheck(Player1,STATE_HELPLESS)
	!StateCheck(Player1,STATE_CONFUSED)
	!StateCheck(Player1,STATE_PANIC)
	Global("Iadispelpotp1","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpotp1","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	Global("Iadispelpot","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadispelpot","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp1fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp1t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player1)
	!StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player1,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap1nr","GLOBAL",0)
	Global("Iacheckp1fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp1t","LOCALS")
	OR(2)
		CheckStatGT(Player1,0,MINORGLOBE)
		HasBounceEffects(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp1fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp2fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp2t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player2)
	!StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player2,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap2nr","GLOBAL",0)
	Global("Iacheckp2fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp2t","LOCALS")
	OR(2)
		CheckStatGT(Player2,0,MINORGLOBE)
		HasBounceEffects(Player2)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp2fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp3fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp3t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player3)
	!StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player3,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap3nr","GLOBAL",0)
	Global("Iacheckp3fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp3t","LOCALS")
	OR(2)
		CheckStatGT(Player3,0,MINORGLOBE)
		HasBounceEffects(Player3)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp3fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp4fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp4t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player4)
	!StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player4,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap4nr","GLOBAL",0)
	Global("Iacheckp4fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp4t","LOCALS")
	OR(2)
		CheckStatGT(Player4,0,MINORGLOBE)
		HasBounceEffects(Player4)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp4fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp5fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp5t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player5)
	!StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player5,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap5nr","GLOBAL",0)
	Global("Iacheckp5fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp5t","LOCALS")
	OR(2)
		CheckStatGT(Player5,0,MINORGLOBE)
		HasBounceEffects(Player5)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp5fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",0)
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		SetGlobal("Iacheckp6fr","LOCALS",1)
		SetGlobalTimer("Iarubyonp6t","LOCALS",ONE_ROUND)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(Player6)
	!StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
	!StateCheck(Player6,STATE_INVISIBLE)
	GlobalLT("Iareversal","LOCALS",9)
	Global("Iap6nr","GLOBAL",0)
	Global("Iacheckp6fr","LOCALS",1)
	GlobalTimerExpired("Iarubyonp6t","LOCALS")
	OR(2)
		CheckStatGT(Player6,0,MINORGLOBE)
		HasBounceEffects(Player6)
THEN
	RESPONSE #100
		IncrementGlobal("Iareversal","LOCALS",1)
		SetGlobal("Iacheckp6fr","LOCALS",0)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (红宝石逆转射线)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("truesight","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
THEN
	RESPONSE #100
		SetGlobalTimer("truesight","LOCALS",ONE_TURN)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (真实视域)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
	Global("Iadra12","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra12","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See([PC])
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // 法术启动－已用出
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(SecondNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // 法术启动－已用出
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	Global("Iapcastts","GLOBAL",0)
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // 法术启动－已用出
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(FourthNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // 法术启动－已用出
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(FifthNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // 法术启动－已用出
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(SixthNearest([PC]))
	!HPLT(Myself,2)
	Global("Iadra03","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("Iadra03","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39968)  // 法术启动－已用出
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iacometb","LOCALS")
	See([PC])
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	GlobalLT("Iacometbreath","LOCALS",4)
THEN
	RESPONSE #70
		IncrementGlobal("Iacometbreath","LOCALS",1)
		SetGlobalTimer("Iacometb","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
	RESPONSE #30
		IncrementGlobal("Iacometbreath","LOCALS",1)
		SetGlobalTimer("Iacometb","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iacometb","LOCALS")
	See(SecondNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	GlobalLT("Iacometbreath","LOCALS",4)
THEN
	RESPONSE #70
		IncrementGlobal("Iacometbreath","LOCALS",1)
		SetGlobalTimer("Iacometb","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
	RESPONSE #30
		IncrementGlobal("Iacometbreath","LOCALS",1)
		SetGlobalTimer("Iacometb","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iacometb","LOCALS")
	See(ThirdNearest([PC]))
	CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	GlobalLT("Iacometbreath","LOCALS",4)
THEN
	RESPONSE #70
		IncrementGlobal("Iacometbreath","LOCALS",1)
		SetGlobalTimer("Iacometb","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
	RESPONSE #30
		IncrementGlobal("Iacometbreath","LOCALS",1)
		SetGlobalTimer("Iacometb","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	!HasBounceEffects(LastSeenBy(Myself))
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	GlobalLT("Iafinger","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Iafinger","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	OR(3)
		CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
		CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
		CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
	GlobalLT("Summon","LOCALS",6)
THEN
	RESPONSE #100
		IncrementGlobal("Summon","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (死亡术)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iahlas","LOCALS")
	!GlobalTimerNotExpired("Iacshlas","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	GlobalLT("Iacshla","LOCALS",9)
THEN
	RESPONSE #100
		IncrementGlobal("Iacshla","LOCALS",1)
		SetGlobalTimer("Iacshlas","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iahlas","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)  // SPCL905.SPL (致命一击)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iahlas","LOCALS")
	!GlobalTimerNotExpired("Iagwhlas","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),5)
	GlobalLT("Iagwhla","LOCALS",9)
THEN
	RESPONSE #100
		IncrementGlobal("Iagwhla","LOCALS",1)
		SetGlobalTimer("Iagwhlas","LOCALS",FOUR_ROUNDS)
		SetGlobalTimer("Iahlas","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)  // SPCL901.SPL (强力旋风攻击)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	OR(2)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	Global("Ianoward","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Ianoward","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_STUNNED)
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_PANIC)
	OR(3)
		CheckStatGT(LastSeenBy(Myself),99,MAGICDAMAGERESISTANCE)
		CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE15)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
	Global("Iaremove","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("Iaremove","LOCALS",2)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!HPLT(Myself,2)
	See([PC])
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
	Global("Iadra04","LOCALS",0)
	Global("Iapcastts","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("Iadra04","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // 法术定序－已用出
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (毒咒)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)  // SPWI401.SPL (困惑术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (缓慢术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // 波塞东的愤怒+5
	GlobalLT("Iawilting","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // 波塞东的愤怒+5
	GlobalLT("Iawilting","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // 波塞东的愤怒+5
	GlobalLT("Iawilting","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	!GlobalTimerNotExpired("Iaadhwtime","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
	!HasItemEquiped("S!halb02",LastSeenBy(Myself))  // 波塞东的愤怒+5
	GlobalLT("Iawilting","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("Iawilting","LOCALS",1)
		SetGlobalTimer("Iaadhwtime","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iadra07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (情绪控制：绝望)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iadra07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (情绪控制：绝望)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
	!CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	GlobalLT("Iadra07","LOCALS",4)
THEN
	RESPONSE #100
		IncrementGlobal("Iadra07","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)  // SPWI411.SPL (情绪控制：绝望)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
END

IF
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	!HasBounceEffects(LastSeenBy(Myself))
	GlobalLT("Iafarrow","LOCALS",5)
THEN
	RESPONSE #100
		IncrementGlobal("Iafarrow","LOCALS",1)
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (火焰箭)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // 魔邓肯之剑
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HPLT(Myself,2)
	GlobalLT("Iamissile","LOCALS",9)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // 魔邓肯之剑
	!HPLT(Myself,2)
	GlobalLT("Iamissile","LOCALS",9)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	!GlobalTimerNotExpired("Iaspell","LOCALS")
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
	CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("morsword",LastSeenBy(Myself))  // 魔邓肯之剑
	!HPLT(Myself,2)
	GlobalLT("Iamissile","LOCALS",9)
THEN
	RESPONSE #100
		SetGlobalTimer("Iaspell","LOCALS",ONE_ROUND)
		IncrementGlobal("Iamissile","LOCALS",1)
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	Allegiance(Myself,ENEMY)
	!CheckStatGT(Myself,0,AURACLEANSING)
	ActionListEmpty()
	!HPLT(Myself,2)
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	RandomNumGT(6,4)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	See(NearestEnemyOf(Myself))
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HPLT(Myself,2)
	ActionListEmpty()
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

