IF
  See(NearestEnemyOfType([PC]))
  Global("Talked","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Talked","LOCALS",1)
    SetGlobalTimer("TooLong","LOCALS",600)
    SelectWeaponAbility(SLOT_WEAPON1,0)
    SelectWeaponAbility(SLOT_WEAPON0,0)
    StartDialogNoSet(NearestEnemyOfType([PC]))
END

IF 
  Global("KuroisanLeave","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("KuroisanLeave","LOCALS",1)
    SetGlobalTimer("KuroisanLeaveTimer","LOCALS",EIGHT_HOURS)
END

IF 
  GlobalTimerExpired("KuroisanLeaveTimer","LOCALS")
THEN 
  RESPONSE #100
    SetGlobal("KuroisanLeave","LOCALS",0)
    SetGlobal("KuroiSpawn","GLOBAL",0)
    DestroySelf()
END 

IF
  GlobalTimerExpired("TooLong","LOCALS")
  Global("Talked","LOCALS",1)
THEN
  RESPONSE #100
    CreateVisualEffectObject("SPPORTAL",Myself)
    DisplayString(Myself,34746)  // ~Damn thy soul, upstart! I've not finished with you!~
    SetGlobal("KuroiAlready","GLOBAL",1)
    SetGlobal("KuroiSpawn","GLOBAL",0)
    DestroySelf()
END

IF
  Global("Prep","LOCALS",0)
  See(NearestEnemyOf(Myself))
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    DisplayString(Myself,56010)  // ~I intend to destroy you.~
    SetGlobal("Prep","LOCALS",1)
    SetGlobalTimer("MO_ProtectionTimer","LOCALS",20)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)    
    ReallyForceSpell(Myself,WIZARD_IMPROVED_MANTLE)
    ReallyForceSpell(Myself,WIZARD_BLUR)
    ReallyForceSpell(Myself,WIZARD_RESIST_FEAR)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
    // IWD Prebuff
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
    SetGlobal("MO_AcidScroll","LOCALS",3)
    CreateCreature("mosol01",[-1.-1],10)
    CreateCreature("mosol02",[-1.-1],10)
    CreateCreature("mosol03",[-1.-1],10)
END

IF
  Global("Prep","LOCALS",0)
  See(NearestEnemyOf(Myself))
  Difficulty(HARD)
THEN
  RESPONSE #40
    DisplayString(Myself,56010)  // ~I intend to destroy you.~
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
    CreateCreature("mosol01",[-1.-1],10)
    SetGlobal("MO_AcidScroll","LOCALS",2)
    DestroyItem("MORB03")
  RESPONSE #30
    DisplayString(Myself,56010)  // ~I intend to destroy you.~
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
    CreateCreature("mosol02",[-1.-1],10)
    SetGlobal("MO_AcidScroll","LOCALS",2)
    DestroyItem("MORB03")
  RESPONSE #30
    DisplayString(Myself,56010)  // ~I intend to destroy you.~
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
    CreateCreature("mosol03",[-1.-1],10)
    SetGlobal("MO_AcidScroll","LOCALS",2)
    DestroyItem("MORB03")
END

IF
  Global("Prep","LOCALS",0)
  See(NearestEnemyOf(Myself))
  DifficultyLT(HARD)
THEN
  RESPONSE #100
    DisplayString(Myself,56010)  // ~I intend to destroy you.~
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_SPELL_SHIELD)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
    SetGlobal("MO_AcidScroll","LOCALS",1)
    DestroyItem("MORB03")
    DestroyItem("MOBT09")
END

//Change1 by LZ
IF
	OR(4)
		StateCheck(Myself,STATE_SLEEPING)
		StateCheck(Myself,STATE_HELPLESS)
		StateCheck(Myself,STATE_BLIND)
		!CheckStat(Myself,0,POLYMORPHED)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_TRUE_DISPEL_MAGIC)  // SPWI326.SPL (解除魔法)
END

IF
	Allegiance(Myself,ENEMY)
	OR(4)
		SpellCastPriest([ANYONE],CLERIC_MISCAST_MAGIC)  // SPPR310.SPL (封魔术)
		SpellCastPriest([ANYONE],CLERIC_SUMMON_INSECTS)  // SPPR319.SPL (召唤昆虫)
		SpellCastPriest([ANYONE],CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (疫病虫群)
		SpellCastPriest([ANYONE],CLERIC_CREEPING_DOOM)  // SPPR717.SPL (漫天虫蚀)
	!GlobalTimerNotExpired("SOSStateTimer","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("SOSStateTimer","LOCALS",ONE_ROUND)
END

IF
	GlobalTimerNotExpired("SOSStateTimer","LOCALS")
	CheckStatGT(Myself,49,SPELLFAILUREMAGE)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_TRUE_DISPEL_MAGIC)  // SPWI326.SPL (解除魔法)
		Wait(2)
END

IF
	SpellCastPriest(Player1,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player1)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player1,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player2,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player2)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player2,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player3,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player3)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player3,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player4,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player4)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player4,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player5,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player5)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player5,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	SpellCastPriest(Player6,CLERIC_HARM)  // SPPR608.SPL (伤害术)
	HasItem("HARM",Player6)  // 伤害术
THEN
	RESPONSE #100
		ReallyForceSpell(Player6,WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	OR(6)
		CheckStatLT(Myself,13,STR)
		CheckStatLT(Myself,12,DEX)
		CheckStatLT(Myself,13,CON)
		CheckStatLT(Myself,12,INT)
		CheckStatLT(Myself,6,WIS)
		CheckStatLT(Myself,6,CHR)
THEN
	RESPONSE #100
		CreateVisualEffectObject("SPPORTAL",Myself)
		DisplayString(Myself,34746)  // 傲慢的家伙，我诅咒你的灵魂！我不会就这么放过你的！
		SetGlobal("KuroiAlready","GLOBAL",1)
		SetGlobal("KuroiSpawn","GLOBAL",0)
		DestroySelf()
END

IF
	See(NearestEnemyOf(Myself))
	HitBy([GOODCUTOFF],CRUSHING)
	Global("Contingency","LOCALS",0)
THEN
	RESPONSE #100
		DisplayString(Myself,40252)  // 意外术－防护魔法武器
		ApplySpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
		SetGlobal("Contingency","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Run from Aerial Denial Spells/Zones
/////////////////////////////////////////////////////////////////////
IF
  !CheckSpellState(Myself,AREA_DENIAL)
  Global("MO_AreaDenial","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",0)
    SetGlobal("MO_AreaDenialOnPC","LOCALS",0)
    MoveToOffset([0.0])
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  !Detect([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  Global("MO_AreaDenial","LOCALS",0)
  CheckStatLT(Player1,1,SANCTUARY)
  !StateCheck(Player1,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    MoveToObject(Player1)
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  !Detect([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  Global("MO_AreaDenial","LOCALS",0)
  CheckStatLT(Player2,1,SANCTUARY)
  !StateCheck(Player2,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    MoveToObject(Player2)
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  !Detect([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  Global("MO_AreaDenial","LOCALS",0)
  CheckStatLT(Player3,1,SANCTUARY)
  !StateCheck(Player3,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    MoveToObject(Player3)
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  !Detect([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  Global("MO_AreaDenial","LOCALS",0)
  CheckStatLT(Player4,1,SANCTUARY)
  !StateCheck(Player4,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    MoveToObject(Player4)
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  !Detect([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  Global("MO_AreaDenial","LOCALS",0)
  CheckStatLT(Player5,1,SANCTUARY)
  !StateCheck(Player5,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    MoveToObject(Player5)
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  !Detect([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  Global("MO_AreaDenial","LOCALS",0)
  CheckStatLT(Player6,1,SANCTUARY)
  !StateCheck(Player6,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    MoveToObject(Player6)
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  See([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_APPROACHABLE)
  Global("MO_AreaDenial","LOCALS",0)
  !Range(LastSeenBy(Myself),5)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    MoveToObject(LastSeenBy(Myself))
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  See([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  StateCheck(LastSeenBy(Myself),STATE_NOT_APPROACHABLE)
   //Global("MO_AreaDenial","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),30)
END

IF
  !GlobalTimerNotExpired("MO_AreaDenialTimer","LOCALS")
  See([PC])
  CheckSpellState(Myself,AREA_DENIAL)
  OR(2)
    Range(LastSeenBy(Myself),5)
    Global("MO_AreaDenialOnPC","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("MO_AreaDenial","LOCALS",1)
    SetGlobal("MO_AreaDenialOnPC","LOCALS",1)
    SetGlobalTimer("MO_AreaDenialTimer","LOCALS",6)
    RunAwayFromNoLeaveArea(LastSeenBy(Myself),30)
END  

/////////////////////////////////////////////////////////////////////
// Hunt the Player
/////////////////////////////////////////////////////////////////////
IF
  !Detect([PC])
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player1,1,SANCTUARY)
  !StateCheck(Player1,STATE_REALLY_DEAD)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",6)
    ReallyForceSpell(Player1,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([PC])
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player2,1,SANCTUARY)
  !StateCheck(Player2,STATE_REALLY_DEAD)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",6)
    ReallyForceSpell(Player2,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([PC])
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player3,1,SANCTUARY)
  !StateCheck(Player3,STATE_REALLY_DEAD)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",6)
    ReallyForceSpell(Player3,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([PC])
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player4,1,SANCTUARY)
  !StateCheck(Player4,STATE_REALLY_DEAD)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",6)
    ReallyForceSpell(Player4,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([PC])
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player5,1,SANCTUARY)
  !StateCheck(Player5,STATE_REALLY_DEAD)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",6)
    ReallyForceSpell(Player5,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([PC])
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("MO_TeleportToPlayerTimer","LOCALS")
  CheckStatLT(Player6,1,SANCTUARY)
  !StateCheck(Player6,STATE_REALLY_DEAD)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_TeleportToPlayerTimer","LOCALS",6)
    ReallyForceSpell(Player6,WIZARD_DIMENSION_DOOR)  // SPWI402.SPL (Dimension Door)
  RESPONSE #100
    Continue()
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player1,1,SANCTUARY)
  !StateCheck(Player1,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player1)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player2,1,SANCTUARY)
  !StateCheck(Player2,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player2)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player3,1,SANCTUARY)
  !StateCheck(Player3,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player3)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player4,1,SANCTUARY)
  !StateCheck(Player4,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player4)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player5,1,SANCTUARY)
  !StateCheck(Player5,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player5)
END

IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
  CheckStatLT(Player6,1,SANCTUARY)
  !StateCheck(Player6,STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player6)
END

IF
    GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
    !Detect([GOODCUTOFF])
    Allegiance(Myself,ENEMY)
THEN
    RESPONSE #100
END

/////////////////////////////////////////////////////////////////////
// Defensive
/////////////////////////////////////////////////////////////////////
//Change2 by LZ
IF
	OR(2)
		!GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,81)
	HasItemEquiped("SCRL7O",Myself)  // 防护魔法武器
	!CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
	!CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
	!CheckSpellState(Myself,MANTLE)
	!CheckSpellState(Myself,IMPROVED_MANTLE)
	GlobalGT("sopfmwcount","LOCALS",2)
	GlobalLT("sopfmwcount","LOCALS",8)
THEN
	RESPONSE #20
		IncrementGlobal("sopfmwcount","LOCALS",1)
		SetGlobalTimer("MO_SpellCastTimer","LOCALS",ONE_ROUND)
		SetInterrupt(FALSE)
		UseItem("SCRL7O",Myself)  // 防护魔法武器
		ReallyForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (痊愈术)
		ForceSpellRES("SPCL901",Myself)  // 强力旋风攻击
		SetInterrupt(TRUE)
	RESPONSE #20
		IncrementGlobal("sopfmwcount","LOCALS",1)
		SetGlobalTimer("MO_SpellCastTimer","LOCALS",ONE_ROUND)
		SetInterrupt(FALSE)
		UseItem("SCRL7O",Myself)  // 防护魔法武器
		ReallyForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (痊愈术)
		ForceSpellRES("SPWI613",Myself)  // 高等加速术
		ForceSpellRES("SPWI615",LastAttackerOf(Myself))  // 连环闪电
		SetInterrupt(TRUE)
	RESPONSE #40
		IncrementGlobal("sopfmwcount","LOCALS",1)
		SetGlobalTimer("MO_SpellCastTimer","LOCALS",ONE_ROUND)
		SetInterrupt(FALSE)
		UseItem("SCRL7O",Myself)  // 防护魔法武器
		ReallyForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (痊愈术)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (镜影术)
		ForceSpellRES("SPWI405",Myself)  // 高等隐形术
		ForceSpellRES("SPWI716",Myself)  // 魔邓肯之剑
		SetInterrupt(TRUE)
	RESPONSE #20
		IncrementGlobal("sopfmwcount","LOCALS",1)
		SetGlobalTimer("MO_SpellCastTimer","LOCALS",ONE_ROUND)
		SetInterrupt(FALSE)
		UseItem("SCRL7O",Myself)  // 防护魔法武器
		ReallyForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (痊愈术)
		ForceSpellRES("SPWI924",Myself)  // 召唤深渊界侍者
		SetInterrupt(TRUE)
END

IF
	See(NearestEnemyOf(Myself))
	HPPercentLT(Myself,81)
	HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
	!CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
	!CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
	!CheckSpellState(Myself,MANTLE)
	!CheckSpellState(Myself,IMPROVED_MANTLE)
	GlobalLT("sopfmwcount","LOCALS",3)
THEN
	RESPONSE #25
		IncrementGlobal("sopfmwcount","LOCALS",1)
		SetInterrupt(FALSE)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
		ReallyForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (痊愈术)
		ForceSpellRES("SPWI909",Myself)  // 时间停止
		ForceSpellRES("SPWI615",LastAttackerOf(Myself))  // 连环闪电
		SetInterrupt(TRUE)
	RESPONSE #25
		IncrementGlobal("sopfmwcount","LOCALS",1)
		SetInterrupt(FALSE)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
		ReallyForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (痊愈术)
		ForceSpellRES("SPWI909",Myself)  // 时间停止
		ForceSpellRES("SPWI915",Myself)  // 毁灭魔剑
		SetInterrupt(TRUE)
	RESPONSE #50
		IncrementGlobal("sopfmwcount","LOCALS",1)
		SetInterrupt(FALSE)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
		ReallyForceSpell(Myself,CLERIC_HEAL)  // SPPR607.SPL (痊愈术)
		ForceSpellRES("SPWI909",Myself)  // 时间停止
		ForceSpellRES("SPWI921",Myself)  // 高等迅捷
		ForceSpellRES("SPWI922",LastAttackerOf(Myself))  // 龙息
		ForceSpellRES("SPWI925",LastAttackerOf(Myself))  // 彗星术
		ForceSpellRES("SPWI812",LastAttackerOf(Myself))  // 亚比达奇凋死术
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(NearestEnemyOf(Myself))
	CheckStatLT(Myself,1,STONESKINS)
	HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
	CheckStatLT(Myself,40,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_POISONED)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckSpellState(Myself,WILD_MAGIC_AREA)
	!CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
	RESPONSE #100
		SetGlobalTimer("MO_SpellCastTimer","LOCALS",ONE_ROUND)
		SetInterrupt(FALSE)
		Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
		SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Death Fog
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak SixthNearestEnemyOf
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SixthNearestEnemyOf
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTACID)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak FifthNearestEnemyOf
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FifthNearestEnemyOf
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTACID)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak FourthNearestEnemyOf
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FourthNearestEnemyOf
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTACID)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak ThirdNearestEnemyOf
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting ThirdNearestEnemyOf
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTACID)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak SecondNearestEnemyOf
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SecondNearestEnemyOf
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTACID)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak NearestEnemyOf
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting NearestEnemyOf
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTACID)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak SixthNearestEnemyOf
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SixthNearestEnemyOf
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,RESISTACID)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak FifthNearestEnemyOf
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FifthNearestEnemyOf
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,RESISTACID)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak FourthNearestEnemyOf
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FourthNearestEnemyOf
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,RESISTACID)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak ThirdNearestEnemyOf
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting ThirdNearestEnemyOf
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,RESISTACID)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak SecondNearestEnemyOf
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SecondNearestEnemyOf
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,RESISTACID)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak NearestEnemyOf
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting NearestEnemyOf
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),40,RESISTACID)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak SixthNearestEnemyOf
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SixthNearestEnemyOf
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTACID)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak FifthNearestEnemyOf
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FifthNearestEnemyOf
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTACID)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak FourthNearestEnemyOf
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FourthNearestEnemyOf
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTACID)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak ThirdNearestEnemyOf
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting ThirdNearestEnemyOf
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTACID)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak SecondNearestEnemyOf
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SecondNearestEnemyOf
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTACID)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  //EEex Offset Casting Mirror Cloak NearestEnemyOf
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting NearestEnemyOf
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTACID)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(EASY)
  //EEex Offset Casting Mirror Cloak SixthNearestEnemyOf
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SixthNearestEnemyOf
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(SixthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(EASY)
  //EEex Offset Casting Mirror Cloak FifthNearestEnemyOf
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FifthNearestEnemyOf
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(FifthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(EASY)
  //EEex Offset Casting Mirror Cloak FourthNearestEnemyOf
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FourthNearestEnemyOf
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(FourthNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(EASY)
  //EEex Offset Casting Mirror Cloak ThirdNearestEnemyOf
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting ThirdNearestEnemyOf
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(ThirdNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(EASY)
  //EEex Offset Casting Mirror Cloak SecondNearestEnemyOf
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SecondNearestEnemyOf
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(SecondNearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(EASY)
  //EEex Offset Casting Mirror Cloak NearestEnemyOf
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting NearestEnemyOf
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(NearestEnemyOf(Myself),Range(NearestAllyOf(Myself),15))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(NORMAL)
  //EEex Offset Casting Mirror Cloak SixthNearestEnemyOf
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SixthNearestEnemyOf
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(SixthNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(NORMAL)
  //EEex Offset Casting Mirror Cloak FifthNearestEnemyOf
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FifthNearestEnemyOf
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(FifthNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(NORMAL)
  //EEex Offset Casting Mirror Cloak FourthNearestEnemyOf
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FourthNearestEnemyOf
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(FourthNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(NORMAL)
  //EEex Offset Casting Mirror Cloak ThirdNearestEnemyOf
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting ThirdNearestEnemyOf
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(ThirdNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(NORMAL)
  //EEex Offset Casting Mirror Cloak SecondNearestEnemyOf
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SecondNearestEnemyOf
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(SecondNearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(NORMAL)
  //EEex Offset Casting Mirror Cloak NearestEnemyOf
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting NearestEnemyOf
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(NearestEnemyOf(Myself),Range(SecondNearestAllyOf(Myself),15))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(HARD)
  //EEex Offset Casting Mirror Cloak SixthNearestEnemyOf
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SixthNearestEnemyOf
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(SixthNearestEnemyOf(Myself),Range(ThirdNearestAllyOf(Myself),15))
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(HARD)
  //EEex Offset Casting Mirror Cloak FifthNearestEnemyOf
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FifthNearestEnemyOf
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(FifthNearestEnemyOf(Myself),Range(ThirdNearestAllyOf(Myself),15))
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(HARD)
  //EEex Offset Casting Mirror Cloak FourthNearestEnemyOf
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting FourthNearestEnemyOf
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(FourthNearestEnemyOf(Myself),Range(ThirdNearestAllyOf(Myself),15))
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(HARD)
  //EEex Offset Casting Mirror Cloak ThirdNearestEnemyOf
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting ThirdNearestEnemyOf
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(ThirdNearestEnemyOf(Myself),Range(ThirdNearestAllyOf(Myself),15))
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(HARD)
  //EEex Offset Casting Mirror Cloak SecondNearestEnemyOf
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting SecondNearestEnemyOf
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(SecondNearestEnemyOf(Myself),Range(ThirdNearestAllyOf(Myself),15))
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_AcidScroll","LOCALS",0)
  DifficultyGT(HARD)
  //EEex Offset Casting Mirror Cloak NearestEnemyOf
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  //EEex Offset Casting NearestEnemyOf
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  !CheckStatGT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),20,RESISTACID)
  TriggerOverride(NearestEnemyOf(Myself),Range(ThirdNearestAllyOf(Myself),15))
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_DeathFogTimer","LOCALS")
  GlobalGT("MO_AcidScroll","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  //EEex Offset Casting Mirror Cloak LastSeenBy
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  //EEex Offset Casting LastSeenBy
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !CheckStatGT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,RESISTACID)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_DeathFogTimer","LOCALS",18)
    IncrementGlobal("MO_AcidScroll","LOCALS",-1)
    DisplayStringHead(Myself,46153)  // ~uses a scroll~
    SetInterrupt(FALSE)
    EEex_SpellObjectOffsetNoDec(LastSeenBy(Myself),WIZARD_DEATH_FOG,[-1.-1])
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Shadow Door
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_ShadowCast","LOCALS")
  HaveSpell(WIZARD_SHADOW_DOOR)
  See(Myself)
  Allegiance(Myself,ENEMY)
  OR(2)
    See(NearestEnemyOf(Myself))
    HitBy([GOODCUTOFF],CRUSHING)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_ShadowCast","LOCALS",32)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SHADOW_DOOR)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Kai
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING) 
  DifficultyGT(NORMAL)
  HaveSpell(KENSAI_KIA)
  Range(SixthNearestEnemyOf(Myself),6)
  !CheckSpellState(Myself,KENSAI_KIA)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  CheckStatGT(SixthNearestEnemyOf(Myself),-20,ARMORCLASS)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  See(SixthNearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING) 
  DifficultyGT(NORMAL)
  HaveSpell(KENSAI_KIA)
  Range(FifthNearestEnemyOf(Myself),6)
  !CheckSpellState(Myself,KENSAI_KIA)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  CheckStatGT(FifthNearestEnemyOf(Myself),-20,ARMORCLASS)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  See(FifthNearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING) 
  DifficultyGT(NORMAL)
  HaveSpell(KENSAI_KIA)
  Range(FourthNearestEnemyOf(Myself),6)
  !CheckSpellState(Myself,KENSAI_KIA)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  CheckStatGT(FourthNearestEnemyOf(Myself),-20,ARMORCLASS)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  See(FourthNearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING) 
  DifficultyGT(NORMAL)
  HaveSpell(KENSAI_KIA)
  Range(ThirdNearestEnemyOf(Myself),6)
  !CheckSpellState(Myself,KENSAI_KIA)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  CheckStatGT(ThirdNearestEnemyOf(Myself),-20,ARMORCLASS)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  See(ThirdNearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING) 
  DifficultyGT(NORMAL)
  HaveSpell(KENSAI_KIA)
  Range(SecondNearestEnemyOf(Myself),6)
  !CheckSpellState(Myself,KENSAI_KIA)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  CheckStatGT(SecondNearestEnemyOf(Myself),-20,ARMORCLASS)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  See(SecondNearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING) 
  DifficultyGT(NORMAL)
  HaveSpell(KENSAI_KIA)
  Range(NearestEnemyOf(Myself),6)
  !CheckSpellState(Myself,KENSAI_KIA)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  CheckStatGT(NearestEnemyOf(Myself),-20,ARMORCLASS)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(LastSeenBy(Myself))
  DifficultyGT(NORMAL)
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(KENSAI_KIA)
  Range(LastSeenBy(Myself),6)
  !CheckSpellState(Myself,KENSAI_KIA)
  CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
  CheckStatGT(LastSeenBy(Myself),-20,ARMORCLASS)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,KENSAI_KIA)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Heal!
/////////////////////////////////////////////////////////////////////
//Change3 by LZ
IF
	!GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
	Allegiance(Myself,ENEMY)
	HasItem("POTN52",Myself)  // 强力医疗药水
	HPPercentLT(Myself,71)
	CheckStatLT(Myself,71,RESISTSLASHING)
	CheckStatLT(Myself,71,RESISTCRUSHING)
	CheckStatLT(Myself,71,RESISTPIERCING)
	Global("sopfmwcount","LOCALS",8)
THEN
	RESPONSE #100
		SetGlobalTimer("MO_SpellCastTimer","LOCALS",ONE_ROUND)
		SetInterrupt(FALSE)
		UseItem("POTN52",Myself)  // 强力医疗药水
		ReallyForceSpell(Myself,WARRIOR_HARDINESS)  // SPCL907.SPL (强韧)
		SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Remove Magic
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic1(6)")
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SixthNearestEnemyOf
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic1(5)")
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FifthNearestEnemyOf
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic1(4)")
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FourthNearestEnemyOf
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic1(3)")
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting ThirdNearestEnemyOf
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic1(2)")
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SecondNearestEnemyOf
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic1(1)")
  !CheckSpellState(NearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting NearestEnemyOf
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SixthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SixthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic1(6)")
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SixthNearestEnemyOf
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FifthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FifthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic1(5)")
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FifthNearestEnemyOf
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FourthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FourthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic1(4)")
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FourthNearestEnemyOf
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(ThirdNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(ThirdNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic1(3)")
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting ThirdNearestEnemyOf
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SecondNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SecondNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic1(2)")
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SecondNearestEnemyOf
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(NearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(NearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic1(1)")
  !CheckSpellState(NearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting NearestEnemyOf
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic2(6)")
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SixthNearestEnemyOf
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic2(5)")
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FifthNearestEnemyOf
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic2(4)")
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FourthNearestEnemyOf
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic2(3)")
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting ThirdNearestEnemyOf
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic2(2)")
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SecondNearestEnemyOf
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic2(1)")
  !CheckSpellState(NearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting NearestEnemyOf
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SixthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SixthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic2(6)")
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SixthNearestEnemyOf
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FifthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FifthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic2(5)")
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FifthNearestEnemyOf
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FourthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FourthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic2(4)")
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FourthNearestEnemyOf
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(ThirdNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(ThirdNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic2(3)")
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting ThirdNearestEnemyOf
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SecondNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SecondNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic2(2)")
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SecondNearestEnemyOf
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(NearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(NearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic2(1)")
  !CheckSpellState(NearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting NearestEnemyOf
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic3(6)")
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SixthNearestEnemyOf
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic3(5)")
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FifthNearestEnemyOf
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic3(4)")
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FourthNearestEnemyOf
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic3(3)")
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting ThirdNearestEnemyOf
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic3(2)")
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SecondNearestEnemyOf
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(2)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic3(1)")
  !CheckSpellState(NearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting NearestEnemyOf
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SixthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SixthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic3(6)")
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SixthNearestEnemyOf
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FifthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FifthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic3(5)")
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FifthNearestEnemyOf
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FourthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FourthNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic3(4)")
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting FourthNearestEnemyOf
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(ThirdNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(ThirdNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic3(3)")
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting ThirdNearestEnemyOf
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SecondNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SecondNearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic3(2)")
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting SecondNearestEnemyOf
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  OR(4)
    CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(NearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(NearestEnemyOf(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic3(1)")
  !CheckSpellState(NearestEnemyOf(Myself),SI_ABJURATION)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  //EEex Offset Casting NearestEnemyOf
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  EEex_LuaTrigger("return MORemoveMagic1(7)")
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  //EEex Offset Casting LastSeenBy
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    RemoveSpell(WIZARD_DISPEL_MAGIC)
    SetInterrupt(FALSE)
    EEex_SpellObjectOffsetNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC,[-1.-1])
    SetInterrupt(TRUE)
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  !GlobalTimerNotExpired("MO_RemoveMagicGlobalTimer","GLOBAL")
  HaveSpell(WIZARD_DISPEL_MAGIC)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  EEex_LuaTrigger("return MORemoveMagic1(7)")
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  //EEex Offset Casting LastSeenBy
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    RemoveSpell(WIZARD_DISPEL_MAGIC)
    SetInterrupt(FALSE)
    EEex_SpellObjectOffsetNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC,[-1.-1])
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Breach
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(2)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 6
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(2)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 5
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(2)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 4
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(2)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 3
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(2)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 2
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(2)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(NearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 1
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(SixthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SixthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SixthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SixthNearestEnemyOf(Myself),MANTLE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 6
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(FifthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FifthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FifthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FifthNearestEnemyOf(Myself),MANTLE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 5
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(FourthNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(FourthNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(FourthNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(FourthNearestEnemyOf(Myself),MANTLE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 4
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(ThirdNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(ThirdNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(ThirdNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(ThirdNearestEnemyOf(Myself),MANTLE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 3
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(SecondNearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(SecondNearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(SecondNearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(SecondNearestEnemyOf(Myself),MANTLE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 2
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(NearestEnemyOf(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(NearestEnemyOf(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(NearestEnemyOf(Myself),IMPROVED_MANTLE)
    CheckSpellState(NearestEnemyOf(Myself),MANTLE)
  !CheckSpellState(NearestEnemyOf(Myself),SPELL_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  // Tactics Breach 1
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  // Tactics Breach 0
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END
   
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_CombatStripGlobalTimer","GLOBAL")
  !GlobalTimerNotExpired("MO_CombatStripTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","GLOBAL")
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(2)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),BUFF_PRO_DAMAGE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  // Tactics Breach 0
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #200
    Continue()
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_CombatStripGlobalTimer","GLOBAL",6)
    SetGlobalTimer("MO_CombatStripTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Slow 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.THIEF])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.THIEF])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.THIEF]),STATE_SLOWED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.THIEF]),SLOW_IMMUNITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,SANCTUARY)
  //EEex Offset Casting SecondNearest([GOODCUTOFF.0.0.THIEF])
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.THIEF]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.THIEF]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.THIEF]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.THIEF]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.THIEF],STATE_SLOWED)
  !CheckSpellState([GOODCUTOFF.0.0.THIEF],SLOW_IMMUNITY)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,SANCTUARY)
  //EEex Offset Casting [GOODCUTOFF.0.0.THIEF]
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.THIEF],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.THIEF])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.RANGER_ALL])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),STATE_SLOWED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),SLOW_IMMUNITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,SANCTUARY)
  //EEex Offset Casting SecondNearest([GOODCUTOFF.0.0.RANGER_ALL])
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.RANGER_ALL]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.RANGER_ALL]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.RANGER_ALL],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.RANGER_ALL],STATE_SLOWED)
  !CheckSpellState([GOODCUTOFF.0.0.RANGER_ALL],SLOW_IMMUNITY)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,SANCTUARY)
  //EEex Offset Casting [GOODCUTOFF.0.0.RANGER_ALL]
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.RANGER_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.RANGER_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.PALADIN])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.PALADIN])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.PALADIN]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.PALADIN]),STATE_SLOWED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.PALADIN]),SLOW_IMMUNITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,SANCTUARY)
  //EEex Offset Casting SecondNearest([GOODCUTOFF.0.0.PALADIN])
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.PALADIN]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.PALADIN]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.PALADIN]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.PALADIN]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.PALADIN],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.PALADIN],STATE_SLOWED)
  !CheckSpellState([GOODCUTOFF.0.0.PALADIN],SLOW_IMMUNITY)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,SANCTUARY)
  //EEex Offset Casting [GOODCUTOFF.0.0.PALADIN]
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.PALADIN],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.PALADIN])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !Class(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),MONK)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),STATE_SLOWED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),SLOW_IMMUNITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,SANCTUARY)
  //EEex Offset Casting SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL])
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !Class([GOODCUTOFF.0.0.FIGHTER_ALL],MONK)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.FIGHTER_ALL]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.FIGHTER_ALL]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER_ALL],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER_ALL],STATE_SLOWED)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER_ALL],SLOW_IMMUNITY)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,SANCTUARY)
  //EEex Offset Casting [GOODCUTOFF.0.0.FIGHTER_ALL]
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER_ALL],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.FIGHTER_ALL])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !Class(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),MONK)
  !HasItemEquiped("RING09",SecondNearest([GOODCUTOFF.0.0.FIGHTER])) // Ring of Free Action
  !HasItemEquiped("NPSW01",SecondNearest([GOODCUTOFF.0.0.FIGHTER])) // Sword of Avoreen
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),SI_TRANSMUTATION)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_HARMLESS)
  !StateCheck(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),STATE_SLOWED)
  !CheckSpellState(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),SLOW_IMMUNITY)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,SANCTUARY)
  //EEex Offset Casting SecondNearest([GOODCUTOFF.0.0.FIGHTER])
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,MINORGLOBE)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),0,CLERIC_FREE_ACTION)
  !CheckStatGT(SecondNearest([GOODCUTOFF.0.0.FIGHTER]),25,RESISTMAGIC)
  See(SecondNearest([GOODCUTOFF.0.0.FIGHTER]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  !Class([GOODCUTOFF.0.0.FIGHTER],MONK)
  !HasItemEquiped("RING09",[GOODCUTOFF.0.0.FIGHTER]) // Ring of Free Action
  !HasItemEquiped("NPSW01",[GOODCUTOFF.0.0.FIGHTER]) // Sword of Avoreen
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER],SI_TRANSMUTATION)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_HARMLESS)
  !StateCheck([GOODCUTOFF.0.0.FIGHTER],STATE_SLOWED)
  !CheckSpellState([GOODCUTOFF.0.0.FIGHTER],SLOW_IMMUNITY)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,SANCTUARY)
  //EEex Offset Casting [GOODCUTOFF.0.0.FIGHTER]
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,MINORGLOBE)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],0,CLERIC_FREE_ACTION)
  !CheckStatGT([GOODCUTOFF.0.0.FIGHTER],25,RESISTMAGIC)
  See([GOODCUTOFF.0.0.FIGHTER])
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_SlowTimer","LOCALS")
  HaveSpell(WIZARD_SLOW)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("RING09",LastSeenBy(Myself)) // Ring of Free Action
  !HasItemEquiped("NPSW01",LastSeenBy(Myself)) // Sword of Avoreen
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !CheckSpellState(LastSeenBy(Myself),SLOW_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  //EEex Offset Casting LastSeenBy
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_SlowTimer","LOCALS",18)
    SetInterrupt(FALSE)
    EEex_SpellObjectOffsetNoDec(LastSeenBy(Myself),WIZARD_SLOW,[-1.-1])
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// IWD Spell: Vitriolic Sphere
/////////////////////////////////////////////////////////////////////

// IWD Cast Vitriolic Sphere

/////////////////////////////////////////////////////////////////////
// Melf Acid Arrow 
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTACID)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),40,RESISTACID)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  !Gender(SixthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SixthNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  !Gender(FifthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FifthNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  !Gender(FourthNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(FourthNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  !Gender(ThirdNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(ThirdNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  !Gender(SecondNearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(SecondNearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  !HasItem("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  !Gender(NearestEnemyOf(Myself),SUMMONED)
  CheckStatLT(NearestEnemyOf(Myself),10,RESISTACID)
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(NearestEnemyOf(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(NearestEnemyOf(Myself),SI_CONJURATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF 
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_AcidArrowTimer","LOCALS")
  HaveSpell(WIZARD_MELF_ACID_ARROW)
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),80,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_PHYSICAL_MIRROR)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AcidArrowTimer","LOCALS",30)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Magic Missile
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",MostDamagedOf([PC]))
  !HasItemEquiped("shld24",MostDamagedOf([PC]))
  CheckStatLT(MostDamagedOf([PC]),50,RESISTMAGIC)
  CheckStatLT(MostDamagedOf([PC]),80,MAGICDAMAGERESISTANCE)
  !StateCheck(MostDamagedOf([PC]),STATE_NOT_TARGETABLE)
  !CheckSpellState(MostDamagedOf([PC]),SI_EVOCATION)
  CheckStatLT(MostDamagedOf([PC]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(MostDamagedOf([PC]),1,WIZARD_SPELL_TURNING)
  !CheckStat(MostDamagedOf([PC]),1,WIZARD_SPELL_TRAP)
  !CheckStat(MostDamagedOf([PC]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(MostDamagedOf([PC]),ENTROPY_SHIELD)
  !CheckSpellState(MostDamagedOf([PC]),WIZARD_SHIELD)
  !CheckStatGT(MostDamagedOf([PC]),0,SANCTUARY)
  CheckStat(MostDamagedOf([PC]),0,MINORGLOBE)
  HPPercentLT(MostDamagedOf([PC]),50)
  See(MostDamagedOf([PC]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),40,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",MostDamagedOf([PC]))
  !HasItemEquiped("shld24",MostDamagedOf([PC]))
  CheckStatLT(MostDamagedOf([PC]),50,RESISTMAGIC)
  CheckStatLT(MostDamagedOf([PC]),40,MAGICDAMAGERESISTANCE)
  !StateCheck(MostDamagedOf([PC]),STATE_NOT_TARGETABLE)
  !CheckSpellState(MostDamagedOf([PC]),SI_EVOCATION)
  CheckStatLT(MostDamagedOf([PC]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(MostDamagedOf([PC]),1,WIZARD_SPELL_TURNING)
  !CheckStat(MostDamagedOf([PC]),1,WIZARD_SPELL_TRAP)
  !CheckStat(MostDamagedOf([PC]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(MostDamagedOf([PC]),ENTROPY_SHIELD)
  !CheckSpellState(MostDamagedOf([PC]),WIZARD_SHIELD)
  !CheckStatGT(MostDamagedOf([PC]),0,SANCTUARY)
  CheckStat(MostDamagedOf([PC]),0,MINORGLOBE)
  HPPercentLT(MostDamagedOf([PC]),50)
  See(MostDamagedOf([PC]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SixthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SixthNearestEnemyOf(Myself))
  CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(SixthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SixthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SixthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SixthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SixthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FifthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FifthNearestEnemyOf(Myself))
  CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(FifthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FifthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FifthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FifthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FifthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FifthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",FourthNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",FourthNearestEnemyOf(Myself))
  CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(FourthNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(FourthNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(FourthNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(FourthNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(FourthNearestEnemyOf(Myself),0,MINORGLOBE)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",ThirdNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",ThirdNearestEnemyOf(Myself))
  CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(ThirdNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(ThirdNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(ThirdNearestEnemyOf(Myself),0,MINORGLOBE)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",SecondNearestEnemyOf(Myself))
  !HasItemEquiped("shld24",SecondNearestEnemyOf(Myself))
  CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(SecondNearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(SecondNearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(SecondNearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(SecondNearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(SecondNearestEnemyOf(Myself),0,MINORGLOBE)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",NearestEnemyOf(Myself))
  !HasItemEquiped("shld24",NearestEnemyOf(Myself))
  CheckStatLT(NearestEnemyOf(Myself),50,RESISTMAGIC)
  CheckStatLT(NearestEnemyOf(Myself),10,MAGICDAMAGERESISTANCE)
  !StateCheck(NearestEnemyOf(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(NearestEnemyOf(Myself),SI_EVOCATION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(NearestEnemyOf(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(NearestEnemyOf(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(NearestEnemyOf(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(NearestEnemyOf(Myself),ENTROPY_SHIELD)
  !CheckSpellState(NearestEnemyOf(Myself),WIZARD_SHIELD)
  !CheckStatGT(NearestEnemyOf(Myself),0,SANCTUARY)
  CheckStat(NearestEnemyOf(Myself),0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  !HasItemEquiped("clck26",MostDamagedOf([PC]))
  !HasItemEquiped("shld24",MostDamagedOf([PC]))
  CheckStatLT(MostDamagedOf([PC]),50,RESISTMAGIC)
  CheckStatLT(MostDamagedOf([PC]),10,MAGICDAMAGERESISTANCE)
  !StateCheck(MostDamagedOf([PC]),STATE_NOT_TARGETABLE)
  !CheckSpellState(MostDamagedOf([PC]),SI_EVOCATION)
  CheckStatLT(MostDamagedOf([PC]),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(MostDamagedOf([PC]),1,WIZARD_SPELL_TURNING)
  !CheckStat(MostDamagedOf([PC]),1,WIZARD_SPELL_TRAP)
  !CheckStat(MostDamagedOf([PC]),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(MostDamagedOf([PC]),ENTROPY_SHIELD)
  !CheckSpellState(MostDamagedOf([PC]),WIZARD_SHIELD)
  !CheckStatGT(MostDamagedOf([PC]),0,SANCTUARY)
  CheckStat(MostDamagedOf([PC]),0,MINORGLOBE)
  HPPercentLT(MostDamagedOf([PC]),50)
  See(MostDamagedOf([PC]))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(WIZARD_MAGIC_MISSILE)
  See(LastSeenBy(Myself))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),ENTROPY_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SHIELD)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,40,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckSpellState(Myself,WILD_MAGIC_AREA)
  !CheckSpellState(Myself,DEAD_MAGIC_AREA)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SetInterrupt(TRUE)
  RESPONSE #100
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Attack
/////////////////////////////////////////////////////////////////////
IF
  OR(6)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 1

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 2

IF
  DifficultyGT(NORMAL)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SixthNearestEnemyOf(Myself),80,RESISTSLASHING)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SixthNearestEnemyOf(Myself),5)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(NORMAL)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FifthNearestEnemyOf(Myself),80,RESISTSLASHING)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FifthNearestEnemyOf(Myself),5)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(NORMAL)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(FourthNearestEnemyOf(Myself),80,RESISTSLASHING)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  Range(FourthNearestEnemyOf(Myself),5)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(NORMAL)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),80,RESISTSLASHING)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  Range(ThirdNearestEnemyOf(Myself),5)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(NORMAL)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(SecondNearestEnemyOf(Myself),80,RESISTSLASHING)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  Range(SecondNearestEnemyOf(Myself),5)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(NORMAL)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  !StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
  CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
  !StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(NearestEnemyOf(Myself),80,RESISTSLASHING)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  Range(NearestEnemyOf(Myself),5)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

// EEex - Is Moving Check 3

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SixthNearestEnemyOf(Myself),1,SANCTUARY)
  See(SixthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FifthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FifthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
  StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(FourthNearestEnemyOf(Myself),1,SANCTUARY)
  See(FourthNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
  StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(ThirdNearestEnemyOf(Myself),1,SANCTUARY)
  See(ThirdNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
  StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(SecondNearestEnemyOf(Myself),1,SANCTUARY)
  See(SecondNearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

IF
  DifficultyGT(EASY)
  WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
  //WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
  StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
  CheckStatLT(NearestEnemyOf(Myself),1,SANCTUARY)
  See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
    NoAction()
END

//Change4 by LZ
/*这段包含EEex_LuaTrigger由solak1.tph替换，涉及两个function MOIsCasting、MoTargetCompare()
IF
	Global("MO_AttackedSomeone","LOCALS",1)
	EEex_LuaTrigger("return MoTargetCompare()")
THEN
	RESPONSE #100
		SetGlobal("MO_AttackedSomeone","LOCALS",0)
		Continue()
END
*/

// EEex - Target Caster (Melee)

IF
  Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  //WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END

IF
  !Allegiance(Myself,ENEMY)
  See(LastSeenBy(Myself))
  Allegiance(LastSeenBy(Myself),ENEMY)
  WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
  //WeaponCanDamage(LastSeenBy(Myself),MAINHAND)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  OR(2)
    CheckStatLT(Myself,1,SANCTUARY)
    HPPercentGT(Myself,49)
THEN
  RESPONSE #100
    SetGlobal("MO_AttackedSomeone","LOCALS",1)
    AttackReevaluate(LastSeenBy(Myself),30)
END

/////////////////////////////////////////////////////////////////////
// Find them! (Experimental)
/////////////////////////////////////////////////////////////////////
IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  OR(2)
    Global("Prep","LOCALS",1)
    HitBy([GOODCUTOFF],CRUSHING)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player1)
END

IF
  ActionListEmpty()
  See(Player1)
  !See(Player2)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player1,MAINHAND)
  !WeaponCanDamage(Player1,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player2)
END

IF
  ActionListEmpty()
  See(Player2)
  !See(Player3)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player2,MAINHAND)
  !WeaponCanDamage(Player2,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player3)
END

IF
  ActionListEmpty()
  See(Player3)
  !See(Player4)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player3,MAINHAND)
  !WeaponCanDamage(Player3,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player4)
END

IF
  ActionListEmpty()
  See(Player4)
  !See(Player5)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player4,MAINHAND)
  !WeaponCanDamage(Player4,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player5)
END

IF
  ActionListEmpty()
  See(Player5)
  !See(Player6)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player5,MAINHAND)
  !WeaponCanDamage(Player5,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player6)
END

IF
  ActionListEmpty()
  See(Player6)
  !See(Player1)
  Allegiance(Myself,ENEMY)
  !WeaponEffectiveVs(Player6,MAINHAND)
  !WeaponCanDamage(Player6,MAINHAND)
  !GlobalTimerNotExpired("MO_IsMovingTimer","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("MO_IsMovingTimer","LOCALS",6)
    MoveToObject(Player1)
END