IF
	Global("BDN_TALK","LOCALS",0)
	HPPercentLT(Myself,51)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("BDN_TALK","LOCALS",1)
		ClearAllActions()
		StartCutSceneMode()
		StartCutScene("BDNCUT34")
END

IF
	Global("BDAFTERWISH","LOCALS",0)
	Global("BDN_TALK","LOCALS",1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("BDAFTERWISH","LOCALS",1)
		DisplayStringHead(Myself,31659)  // 哇哈哈哈！
		ForceSpellRES("SPWI807",Myself)  // 预知术
		ForceSpellRES("SPWI920",Myself)  // 魔能刃
		ForceSpellRES("SPWI405",Myself)  // 高等隐形术
		ForceSpellRES("SPWI592",Myself)  // 法术免疫：预言系
		SetInterrupt(TRUE)
END

IF
	OR(2)
		Global("BDN_TALK","LOCALS",1)
		Global("BDN_TALK","LOCALS",2)
	!HasItem("eneblade",Myself)  // 魔能刃
	!HasItem("CDMINDFL",Myself)  // 攻击
	RandomNum(20,1)
THEN
	RESPONSE #100
		ForceSpellRES("SPWI920",Myself)  // 魔能刃
END

IF
	Global("BDN_TALK","LOCALS",1)
	HPPercentLT(Myself,11)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetGlobal("BDN_TALK","LOCALS",2)
		ClearAllActions()
		StartCutSceneMode()
		StartCutScene("BDNCUT34")
END

IF
	Global("BDAFTERWISH","LOCALS",1)
	Global("BDN_TALK","LOCALS",2)
	!GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
	Range(LastSeenBy(Myself),4)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("BDAFTERWISH","LOCALS",2)
		DisplayStringHead(Myself,72979)  // 你死定了！
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
		ForceSpellRES("spwi613",Myself)  // 高等加速术
		ForceSpellRES("spwi909",Myself)  // 时间停止
		ReallyForceSpell(Myself,SHAPECHANGE_MIND_FLAYER)  // SPIN152.SPL (变形术：夺心魔)
		Polymorph(MINDFLAYER)
		SetGlobalTimer("MINDFL_TS","LOCALS",THREE_ROUNDS)
		SetInterrupt(TRUE)
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See([PC])
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(SecondNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(ThirdNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(FourthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(FifthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(SixthNearest([PC]))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(NearestEnemyOf(Myself))
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(SecondNearestEnemyOf(Myself))
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(ThirdNearestEnemyOf(Myself))
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(FourthNearestEnemyOf(Myself))
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(FifthNearestEnemyOf(Myself))
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(SixthNearestEnemyOf(Myself))
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
	See(SeventhNearestEnemyOf(Myself))
	WeaponEffectiveVs(LastSeenBy(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	!GlobalTimerNotExpired("MINDFL_TS","LOCALS")
	HasItem("CDMINDFL",Myself)  // 攻击
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,SHAPESHIFT_NATURAL_FORM_2)  // SPIN151.SPL (变回原来形态)
		Polymorph(MEFISTO_ACIFER)
END

IF
	Global("BDN_TALK","LOCALS",2)
	!HasItem("CDMINDFL",Myself)  // 攻击
	Dead("BDSHANG")  // 三体恶魔·贪婪
	Dead("BDLAYEN")  // 三体恶魔·狡诈
	HPPercentLT(Myself,11)
	InMyArea(Player1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("BDN_TALK","LOCALS",3)
		DisplayStringHead(Myself,11131)  // 我要杀了你！
		ReallyForceSpell(Myself,RESTORE_FULL_HEALTH)  // SPIN746.SPL (No such index)
		ForceSpellRES("SPWI405",Myself)  // 高等隐形术
		ForceSpellRES("OHBBCLT3",Myself)  // 掠夺者改变
		Wait(1)
		ChangeAnimationNoEffect("OHBBRVG2")  // 掠夺者
		SetInterrupt(TRUE)
END

IF
	Global("BD_Active","LOCALS",0)
	OR(3)
		AttackedBy([ANYONE],DEFAULT)
		TookDamage()
		Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		SetGlobal("BD_Active","LOCALS",1)
		SetGlobalTimer("BD_Rest","LOCALS",ONE_HOUR)
		Continue()
END

IF
	OR(4)
		Global("BD_Active","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!GlobalTimerNotExpired("BD_Rest","LOCALS")
	!HasItem("CDMINDFL",Myself)  // 攻击
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Rest","LOCALS",ONE_HOUR)
		SetGlobal("BD_CHCntg","LOCALS",0)
		SetGlobal("BD_Cntg","LOCALS",0)
		SetGlobal("BD_Seq","LOCALS",0)
		SetGlobal("BD_MSeq","LOCALS",0)
		SetGlobal("BD_Trig","LOCALS",0)
		ApplySpell(Myself,RESTORE_FULL_HEALTH)  // SPIN746.SPL (No such index)
		Rest()
		SetInterrupt(TRUE)
END

IF
	Global("BD_Active","LOCALS",1)
	Global("BD_CHCntg","LOCALS",0)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("BD_CHCntg","LOCALS",1)
		DisplayString(Myself,26328)  // 连锁意外术
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (防护能量)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (法术反转)
		Continue()
END

IF
	Global("BD_Active","LOCALS",1)
	Global("BD_Cntg","LOCALS",0)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("BD_Cntg","LOCALS",1)
		DisplayString(Myself,8292)  // 意外效果
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
		Continue()
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	Global("BD_Trig","LOCALS",0)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY14)
	Range([GOODCUTOFF],30)
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("BD_Trig","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DisplayString(Myself,26243)  // 法术启动
		ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (真实视域)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (火焰护盾（红）)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (火焰盾（蓝）)
END

IF
	StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (发声术)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (发声术)
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	Global("BD_Seq","LOCALS",0)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY14)
	CheckStatLT(Myself,1,STONESKINS)
	CheckStat(Myself,0,EXTRAPROFICIENCY11)
	Range([GOODCUTOFF],30)
THEN
	RESPONSE #100
		SetGlobal("BD_Seq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // 法术定序－已用出
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (火焰护盾（红）)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (火焰盾（蓝）)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	Global("BDN_REFRESH","LOCALS",0)
	!HaveSpell(WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
	!HaveSpell(WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (高等迅捷)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	GlobalLT("BDNSTWish","LOCALS",3)
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HasItem("CDMINDFL",Myself)  // 攻击
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BDNSTWish","LOCALS",1)
		SetGlobal("BDN_REFRESH","LOCALS",1)
		SetGlobal("BDNWish","GLOBAL",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,100275)  // 摇一个铃
		ForceSpellRES("BDNWISH",Myself)  // 愿望术
		SetGlobal("BD_CHCntg","LOCALS",0)
		SetGlobal("BD_Cntg","LOCALS",0)
		SetGlobal("BD_Seq","LOCALS",0)
		SetGlobal("BD_MSeq","LOCALS",0)
		SetGlobal("BD_Trig","LOCALS",0)
		Wait(1)
		SetInterrupt(TRUE)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	Global("BDN_IATS","LOCALS",0)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	GlobalLT("BDNSTWish","LOCALS",3)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!HasItem("CDMINDFL",Myself)  // 攻击
	DifficultyGT(EASY)
	See(Player1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BDNSTWish","LOCALS",1)
		SetGlobal("BDN_IATS","LOCALS",1)
		SetGlobal("BDNWish","GLOBAL",3)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,100275)  // 摇一个铃
		ForceSpellRES("BDNWISH",Myself)  // 愿望术
		SetGlobalTimer("BD_TStop","LOCALS",SIX_ROUNDS)
		Wait(1)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	GlobalLT("BDNSTWish","LOCALS",3)
	CheckStatGT([PC],0,EXTRAPROFICIENCY5)
	OR(4)
		CheckStatGT(SecondNearest([PC]),0,EXTRAPROFICIENCY5)
		CheckStatGT(ThirdNearest([PC]),0,EXTRAPROFICIENCY5)
		CheckStatGT(FourthNearest([PC]),0,EXTRAPROFICIENCY5)
		CheckStatGT(FifthNearest([PC]),0,EXTRAPROFICIENCY5)
	Global("BDN_Breach","LOCALS",0)
	!HasItem("CDMINDFL",Myself)  // 攻击
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BDNSTWish","LOCALS",1)
		SetGlobal("BDN_Breach","LOCALS",1)
		SetGlobal("BDNWish","GLOBAL",2)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,100275)  // 摇一个铃
		ForceSpellRES("BDNWISH",Myself)  // 愿望术
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	GlobalLT("BDNSTWish","LOCALS",3)
	Global("BDN_Breach","LOCALS",0)
	!HasItem("CDMINDFL",Myself)  // 攻击
	CheckStatGT([PC],0,EXTRAPROFICIENCY12)
	OR(4)
		CheckStatGT(SecondNearest([PC]),0,EXTRAPROFICIENCY12)
		CheckStatGT(ThirdNearest([PC]),0,EXTRAPROFICIENCY12)
		CheckStatGT(FourthNearest([PC]),0,EXTRAPROFICIENCY12)
		CheckStatGT(FifthNearest([PC]),0,EXTRAPROFICIENCY12)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BDNSTWish","LOCALS",1)
		SetGlobal("BDN_Breach","LOCALS",1)
		SetGlobal("BDNWish","GLOBAL",2)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,100275)  // 摇一个铃
		ForceSpellRES("BDNWISH",Myself)  // 愿望术
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	See([PC])
	HaveSpell(WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	!HasItem("CDMINDFL",Myself)  // 攻击
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_TStop","LOCALS",THREE_ROUNDS)
		Spell(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (时间停止)
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (高等迅捷)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([PC])
	!HasItem("CDMINDFL",Myself)  // 攻击
	DifficultyGT(EASY)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (高等迅捷)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY14)
	HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	Range([GOODCUTOFF],30)
	OR(3)
		CheckStatLT(Myself,1,STONESKINS)
		AttackedBy([ANYONE],DEFAULT)
		Range([GOODCUTOFF],4)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (防护魔法武器)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	CheckStatLT(Myself,1,STONESKINS)
	HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (石肤术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DEATH_SPELL)  // SPWI605.SPL (死亡术)
	OR(3)
		See([GOODCUTOFF.0.0.0.0.SUMMONED])
		See([GOODCUTOFF.WEAPON.SWORD.0.0.SUMMONED])
		See([GOODCUTOFF.0.MIST.0.0.SUMMONED])
	OR(3)
		HasItem("MORSWORD",LastSeenBy(Myself))  // 魔邓肯之剑
		HasItem("NISHRUU",LastSeenBy(Myself))  // No such index
		NumCreatureGT([GOODCUTOFF.0.0.0.0.SUMMONED],2)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (死亡术)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	See([GOODCUTOFF.WEAPON.SWORD.0.0.SUMMONED])
	HasItem("MORSWORD",LastSeenBy(Myself))  // 魔邓肯之剑
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
	DifficultyGT(EASY)
	HPLT(Player1,60)
	See(Player1)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player1)  // 魔法屏蔽斗篷
	!CheckStatGT(Player1,0,SANCTUARY)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE2)
	!CheckStatGT(Player1,1,EXTRAPROFICIENCY2)
	!CheckStatGT(Player1,1,EXTRAPROFICIENCY15)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE9)
	!CheckStat(Player1,1,EXTRAPROFICIENCY9)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatLT(Player1,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
	DifficultyGT(EASY)
	HPLT(Player2,60)
	See(Player2)
	!StateCheck(Player2,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player2)  // 魔法屏蔽斗篷
	!CheckStatGT(Player2,0,SANCTUARY)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE2)
	!CheckStatGT(Player2,1,EXTRAPROFICIENCY2)
	!CheckStatGT(Player2,1,EXTRAPROFICIENCY15)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE9)
	!CheckStat(Player2,1,EXTRAPROFICIENCY9)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatLT(Player2,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
	DifficultyGT(EASY)
	HPLT(Player3,60)
	See(Player3)
	!StateCheck(Player3,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player3)  // 魔法屏蔽斗篷
	!CheckStatGT(Player3,0,SANCTUARY)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE2)
	!CheckStatGT(Player3,1,EXTRAPROFICIENCY2)
	!CheckStatGT(Player3,1,EXTRAPROFICIENCY15)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE9)
	!CheckStat(Player3,1,EXTRAPROFICIENCY9)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatLT(Player3,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
	DifficultyGT(EASY)
	HPLT(Player4,60)
	See(Player4)
	!StateCheck(Player4,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player4)  // 魔法屏蔽斗篷
	!CheckStatGT(Player4,0,SANCTUARY)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE2)
	!CheckStatGT(Player4,1,EXTRAPROFICIENCY2)
	!CheckStatGT(Player4,1,EXTRAPROFICIENCY15)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE9)
	!CheckStat(Player4,1,EXTRAPROFICIENCY9)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatLT(Player4,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
	DifficultyGT(EASY)
	HPLT(Player5,60)
	See(Player5)
	!StateCheck(Player5,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player5)  // 魔法屏蔽斗篷
	!CheckStatGT(Player5,0,SANCTUARY)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE2)
	!CheckStatGT(Player5,1,EXTRAPROFICIENCY2)
	!CheckStatGT(Player5,1,EXTRAPROFICIENCY15)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE9)
	!CheckStat(Player5,1,EXTRAPROFICIENCY9)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatLT(Player5,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
	DifficultyGT(EASY)
	HPLT(Player6,60)
	See(Player6)
	!StateCheck(Player6,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player6)  // 魔法屏蔽斗篷
	!CheckStatGT(Player6,0,SANCTUARY)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE2)
	!CheckStatGT(Player6,1,EXTRAPROFICIENCY2)
	!CheckStatGT(Player6,1,EXTRAPROFICIENCY15)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE9)
	!CheckStat(Player6,1,EXTRAPROFICIENCY9)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatLT(Player6,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
	DifficultyGT(EASY)
	OR(3)
		See([GOODCUTOFF])
		See(WeakestOf([GOODCUTOFF]))
		See(MostDamagedOf([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),9,LEVEL)
	HPLT(LastSeenBy(Myself),60)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (律令：死亡)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
	!Difficulty(EASIEST)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	HPLT(Player1,90)
	See(Player1)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!StateCheck(Player1,STATE_HARMLESS)
	!CheckStatGT(Player1,0,EXTRAPROFICIENCY2)
	!CheckStatGT(Player1,0,EXTRAPROFICIENCY15)
	!CheckStatGT(Player1,0,SCRIPTINGSTATE9)
	!CheckStatGT(Player1,0,EXTRAPROFICIENCY5)
	!CheckStatGT(Player1,0,EXTRAPROFICIENCY17)
	!CheckStat(Player1,1,EXTRAPROFICIENCY9)
	!CheckStat(Player1,2,SCRIPTINGSTATE7)
	!CheckStat(Player1,1,SCRIPTINGSTATE4)
	!HasItemEquipedReal("NPSW01",Player1)  // 阿尔孚琳之剑+2
	!HasItemEquipedReal("SW1H27",Player1)  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",Player1)  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",Player1)  // 双手剑+2
	CheckStatLT(Player1,50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
	!Difficulty(EASIEST)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	HPLT(Player2,90)
	See(Player2)
	!StateCheck(Player2,STATE_REALLY_DEAD)
	!StateCheck(Player2,STATE_HARMLESS)
	!CheckStatGT(Player2,0,EXTRAPROFICIENCY2)
	!CheckStatGT(Player2,0,EXTRAPROFICIENCY15)
	!CheckStatGT(Player2,0,SCRIPTINGSTATE9)
	!CheckStatGT(Player2,0,EXTRAPROFICIENCY5)
	!CheckStatGT(Player2,0,EXTRAPROFICIENCY17)
	!CheckStat(Player2,2,SCRIPTINGSTATE7)
	!CheckStat(Player2,1,SCRIPTINGSTATE4)
	!CheckStat(Player2,1,EXTRAPROFICIENCY9)
	!HasItemEquipedReal("NPSW01",Player2)  // 阿尔孚琳之剑+2
	!HasItemEquipedReal("SW1H27",Player2)  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",Player2)  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",Player2)  // 双手剑+2
	CheckStatLT(Player2,50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
	!Difficulty(EASIEST)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	HPLT(Player3,90)
	See(Player3)
	!StateCheck(Player3,STATE_REALLY_DEAD)
	!StateCheck(Player3,STATE_HARMLESS)
	!CheckStatGT(Player3,0,EXTRAPROFICIENCY2)
	!CheckStatGT(Player3,0,EXTRAPROFICIENCY15)
	!CheckStatGT(Player3,0,SCRIPTINGSTATE9)
	!CheckStatGT(Player3,0,EXTRAPROFICIENCY5)
	!CheckStatGT(Player3,0,EXTRAPROFICIENCY17)
	!CheckStat(Player3,2,SCRIPTINGSTATE7)
	!CheckStat(Player3,1,SCRIPTINGSTATE4)
	!CheckStat(Player3,1,EXTRAPROFICIENCY9)
	!HasItemEquipedReal("NPSW01",Player3)  // 阿尔孚琳之剑+2
	!HasItemEquipedReal("SW1H27",Player3)  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",Player3)  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",Player3)  // 双手剑+2
	CheckStatLT(Player3,50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
	!Difficulty(EASIEST)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	HPLT(Player4,90)
	See(Player4)
	!StateCheck(Player4,STATE_REALLY_DEAD)
	!StateCheck(Player4,STATE_HARMLESS)
	!CheckStatGT(Player4,0,EXTRAPROFICIENCY2)
	!CheckStatGT(Player4,0,EXTRAPROFICIENCY15)
	!CheckStatGT(Player4,0,SCRIPTINGSTATE9)
	!CheckStatGT(Player4,0,EXTRAPROFICIENCY5)
	!CheckStatGT(Player4,0,EXTRAPROFICIENCY17)
	!CheckStat(Player4,2,SCRIPTINGSTATE7)
	!CheckStat(Player4,1,SCRIPTINGSTATE4)
	!CheckStat(Player4,1,EXTRAPROFICIENCY9)
	!HasItemEquipedReal("NPSW01",Player4)  // 阿尔孚琳之剑+2
	!HasItemEquipedReal("SW1H27",Player4)  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",Player4)  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",Player4)  // 双手剑+2
	CheckStatLT(Player4,50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
	!Difficulty(EASIEST)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	HPLT(Player5,90)
	See(Player5)
	!StateCheck(Player5,STATE_REALLY_DEAD)
	!StateCheck(Player5,STATE_HARMLESS)
	!CheckStatGT(Player5,0,EXTRAPROFICIENCY2)
	!CheckStatGT(Player5,0,EXTRAPROFICIENCY15)
	!CheckStatGT(Player5,0,SCRIPTINGSTATE9)
	!CheckStatGT(Player5,0,EXTRAPROFICIENCY5)
	!CheckStatGT(Player5,0,EXTRAPROFICIENCY17)
	!CheckStat(Player5,2,SCRIPTINGSTATE7)
	!CheckStat(Player5,1,SCRIPTINGSTATE4)
	!CheckStat(Player5,1,EXTRAPROFICIENCY9)
	!HasItemEquipedReal("NPSW01",Player5)  // 阿尔孚琳之剑+2
	!HasItemEquipedReal("SW1H27",Player5)  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",Player5)  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",Player5)  // 双手剑+2
	CheckStatLT(Player5,50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
	!Difficulty(EASIEST)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	HPLT(Player6,90)
	See(Player6)
	!StateCheck(Player6,STATE_REALLY_DEAD)
	!StateCheck(Player6,STATE_HARMLESS)
	!CheckStatGT(Player6,0,EXTRAPROFICIENCY2)
	!CheckStatGT(Player6,0,EXTRAPROFICIENCY15)
	!CheckStatGT(Player6,0,SCRIPTINGSTATE9)
	!CheckStatGT(Player6,0,EXTRAPROFICIENCY5)
	!CheckStatGT(Player6,0,EXTRAPROFICIENCY17)
	!CheckStat(Player6,2,SCRIPTINGSTATE7)
	!CheckStat(Player6,1,SCRIPTINGSTATE4)
	!CheckStat(Player6,1,EXTRAPROFICIENCY9)
	!HasItemEquipedReal("NPSW01",Player6)  // 阿尔孚琳之剑+2
	!HasItemEquipedReal("SW1H27",Player6)  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",Player6)  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",Player6)  // 双手剑+2
	CheckStatLT(Player6,50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
	!Difficulty(EASIEST)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	HPLT(LastSeenBy(Myself),90)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	CheckStatGT(LastSeenBy(Myself),9,LEVEL)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // 魔邓肯之剑
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (律令：震慑)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See("Keldorn")  // 凯东
	!StateCheck("Keldorn",STATE_REALLY_DEAD)  // 凯东
	!StateCheck("Keldorn",STATE_SILENCED)  // 凯东
	!StateCheck("Keldorn",STATE_HARMLESS)  // 凯东
	!CheckStatGT("Keldorn",0,EXTRAPROFICIENCY15)  // 凯东
	!HasItemEquiped("AMUL21","Keldorn")  // 魔力护符
	CheckStatLT("Keldorn",50,RESISTMAGIC)  // 凯东
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See([PC.0.0.PALADIN_ALL])
	Kit(LastSeenBy(Myself),INQUISITOR)
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See([PC.0.0.MAGE_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See([PC.0.0.DRUID_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.DRUID_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See(ThirdNearest([PC.0.0.DRUID_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See([PC.0.0.CLERIC_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.CLERIC_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See(ThirdNearest([PC.0.0.CLERIC_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See([PC.0.0.BARD_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		CheckStatGT(Myself,0,AURACLEANSING)
		!GlobalTimerNotExpired("BD_PWR","LOCALS")
	HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.BARD_ALL]))
	!StateCheck(LastSeenBy(Myself),STATE_SILENCED)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	!HasItemEquiped("AMUL21",LastSeenBy(Myself))  // 魔力护符
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_PWR","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (律令：沉默)
		SetInterrupt(TRUE)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
	DifficultyGT(EASY)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
	DifficultyGT(EASY)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
	DifficultyGT(EASY)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
	DifficultyGT(EASY)
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
	DifficultyGT(EASY)
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
	DifficultyGT(EASY)
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (龙息)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (彗星术)
	!Difficulty(EASIEST)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (彗星术)
	!Difficulty(EASIEST)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (彗星术)
	!Difficulty(EASIEST)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (彗星术)
	!Difficulty(EASIEST)
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (彗星术)
	!Difficulty(EASIEST)
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (彗星术)
	!Difficulty(EASIEST)
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (彗星术)
END

IF
	!GlobalGT("BDN_TALK","LOCALS",1)
	CheckStatGT(Myself,0,AURACLEANSING)
	GlobalLT("BDN_MMIA","LOCALS",5)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	DifficultyGT(EASY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BDN_MMIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	!GlobalGT("BDN_TALK","LOCALS",1)
	CheckStatGT(Myself,0,AURACLEANSING)
	GlobalLT("BDN_MMIA","LOCALS",5)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	DifficultyGT(EASY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BDN_MMIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	!GlobalGT("BDN_TALK","LOCALS",1)
	CheckStatGT(Myself,0,AURACLEANSING)
	GlobalLT("BDN_MMIA","LOCALS",5)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	DifficultyGT(EASY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BDN_MMIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	GlobalGT("BDN_TALK","LOCALS",1)
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
	GlobalLT("BDN_AAIA","LOCALS",3)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BDN_AAIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
	GlobalLT("BDN_AAIA","LOCALS",3)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BDN_AAIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF.0.MIST.0.0.SUMMONED])
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	See(Player1)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL3)
	OR(11)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY4)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY19)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY11)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	See(Player2)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL3)
	OR(11)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY4)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY19)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY11)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	See(Player3)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL3)
	OR(11)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY4)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY19)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY11)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	See(Player4)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL3)
	OR(11)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY4)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY19)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY11)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	See(Player5)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL3)
	OR(11)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY4)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY19)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY11)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	See(Player6)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),39,LEVEL3)
	OR(11)
		StateCheck(LastSeenBy(Myself),STATE_HASTED)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY4)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY19)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY11)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE5)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (移除魔法)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (毒咒)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (毒咒)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (毒咒)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (毒咒)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (毒咒)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (毒咒)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HasItem("OHNWAND1",Myself)  // 鞭击魔杖
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Wand","LOCALS")
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	CheckStatGT(LastSeenBy(Myself),6,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself))  // 独角兽之矛+2
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Wand","LOCALS",THREE_ROUNDS)
		UseItem("OHNWAND1",LastSeenBy(Myself))  // 鞭击魔杖
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HasItem("OHNWAND1",Myself)  // 鞭击魔杖
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Wand","LOCALS")
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	CheckStatGT(LastSeenBy(Myself),6,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself))  // 独角兽之矛+2
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Wand","LOCALS",THREE_ROUNDS)
		UseItem("OHNWAND1",LastSeenBy(Myself))  // 鞭击魔杖
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HasItem("OHNWAND1",Myself)  // 鞭击魔杖
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Wand","LOCALS")
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	CheckStatGT(LastSeenBy(Myself),6,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself))  // 独角兽之矛+2
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Wand","LOCALS",THREE_ROUNDS)
		UseItem("OHNWAND1",LastSeenBy(Myself))  // 鞭击魔杖
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HasItem("OHNWAND1",Myself)  // 鞭击魔杖
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Wand","LOCALS")
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	CheckStatGT(LastSeenBy(Myself),6,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself))  // 独角兽之矛+2
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Wand","LOCALS",THREE_ROUNDS)
		UseItem("OHNWAND1",LastSeenBy(Myself))  // 鞭击魔杖
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HasItem("OHNWAND1",Myself)  // 鞭击魔杖
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Wand","LOCALS")
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	CheckStatGT(LastSeenBy(Myself),12,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself))  // 独角兽之矛+2
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Wand","LOCALS",THREE_ROUNDS)
		UseItem("OHNWAND1",LastSeenBy(Myself))  // 鞭击魔杖
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	HasItem("OHNWAND1",Myself)  // 鞭击魔杖
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Wand","LOCALS")
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	CheckStatGT(LastSeenBy(Myself),12,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SPER07",LastSeenBy(Myself))  // 独角兽之矛+2
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Wand","LOCALS",THREE_ROUNDS)
		UseItem("OHNWAND1",LastSeenBy(Myself))  // 鞭击魔杖
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		SetInterrupt(TRUE)
END

IF
	Global("BD_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // 次级定序术启动
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (臭云术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	Global("BD_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // 次级定序术启动
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (臭云术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	Global("BD_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // 次级定序术启动
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (臭云术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	Global("BD_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // 次级定序术启动
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (臭云术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	Global("BD_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // 次级定序术启动
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (臭云术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	Global("BD_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // 次级定序术启动
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (臭云术)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_WEB)  // SPWI215.SPL (蛛网术)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_Web","LOCALS")
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		!GlobalTimerNotExpired("BD_TStop","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_WEB)  // SPWI215.SPL (蛛网术)
	!GlobalTimerNotExpired("BD_Web","LOCALS")
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	OR(2)
		!GlobalTimerNotExpired("BD_TStop","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_WEB)  // SPWI215.SPL (蛛网术)
	!GlobalTimerNotExpired("BD_Web","LOCALS")
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobal("BD_MSeq","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_Web","LOCALS",FOUR_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_WEB)  // SPWI215.SPL (蛛网术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
	!Difficulty(EASIEST)
	See(NearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
	!Difficulty(EASIEST)
	See(SecondNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
	!Difficulty(EASIEST)
	See(ThirdNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
	!Difficulty(EASIEST)
	See(FourthNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
	!Difficulty(EASIEST)
	See(FifthNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
	!Difficulty(EASIEST)
	See(SixthNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (亚比达奇凋死术)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_PierceW","LOCALS",6)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY9)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BD_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (识破魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_PierceW","LOCALS",6)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY9)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BD_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (识破魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_PierceW","LOCALS",6)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY9)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BD_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (识破魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_PierceW","LOCALS",6)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY9)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BD_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (识破魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_PierceW","LOCALS",6)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY9)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BD_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (识破魔法)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_PierceW","LOCALS",6)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY9)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("BD_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (识破魔法)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("SCRL9M",Myself)  // 法术重击
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	See([PC.0.0.MAGE_ALL])
	OR(5)
		CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DestroyItem("SCRL9M")  // 法术重击
		DisplayStringHead(Myself,46153)  // 使用卷轴
		SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (法术重击)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("SCRL9M",Myself)  // 法术重击
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	OR(5)
		CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DestroyItem("SCRL9M")  // 法术重击
		DisplayStringHead(Myself,46153)  // 使用卷轴
		SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (法术重击)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("SCRL9M",Myself)  // 法术重击
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	See([PC])
	OR(5)
		CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
		CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
		CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
		CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DestroyItem("SCRL9M")  // 法术重击
		DisplayStringHead(Myself,46153)  // 使用卷轴
		SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (法术重击)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See([PC.0.0.MAGE])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See(SecondNearest([PC.0.0.MAGE]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See([PC.0.0.BARD])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See(SecondNearest([PC.0.0.BARD]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See([PC.0.0.THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See(SecondNearest([PC.0.0.THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See([PC.0.0.MAGE_THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
	See(SecondNearest([PC.0.0.MAGE_THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
	!CheckStat(LastSeenBy(Myself),7,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // 辛度之末日+4
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (死亡一指)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (缓慢术)
	See([GOODCUTOFF])
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (缓慢术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (缓慢术)
	See(SecondNearest([GOODCUTOFF]))
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (缓慢术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (缓慢术)
	See(ThirdNearest([GOODCUTOFF]))
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // 阿尔孚琳之剑+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // 费尔康全身板甲
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,SCRIPTINGSTATE7)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (缓慢术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
	See([GOODCUTOFF])
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // 艾格之皮+3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // 利拉寇尔
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // 平衡者
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // 灵能刃+5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
	See(SecondNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // 艾格之皮+3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // 利拉寇尔
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // 平衡者
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // 灵能刃+5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
	See(ThirdNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // 艾格之皮+3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // 利拉寇尔
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // 平衡者
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // 灵能刃+5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
	See(FourthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // 艾格之皮+3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // 利拉寇尔
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // 平衡者
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // 灵能刃+5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
	See(FifthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // 艾格之皮+3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // 利拉寇尔
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // 平衡者
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // 灵能刃+5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
	See(SixthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // 艾格之皮+3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // 和谐之盾+2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // 利拉寇尔
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // 平衡者
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // 灵能刃+5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (混乱术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
	See([GOODCUTOFF])
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // 魔邓肯之剑
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
	!CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (弱智术)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([PC.0.0.MAGE])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC.0.0.MAGE]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([PC.0.0.MAGE_THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC.0.0.MAGE_THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See([PC.0.0.BARD])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC.0.0.BARD]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),1,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY17)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // 亚班的敏捷之刃+2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // 艾德凡塔的礼物
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // 双手剑+2
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (比格拜巨力拳)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_BreachW","LOCALS",6)
	!GlobalTimerNotExpired("BD_BREACH","LOCALS")
	See([PC])
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY14)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY12)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BD_BreachW","LOCALS",1)
		SetGlobalTimer("BD_BREACH","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		UseItem("WAND18",LastSeenBy(Myself))  // 法术重击之杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	!GlobalTimerNotExpired("BD_BREACH","LOCALS")
	GlobalLT("BD_BreachW","LOCALS",6)
	See(SecondNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY14)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY12)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BD_BreachW","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		UseItem("WAND18",LastSeenBy(Myself))  // 法术重击之杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_BreachW","LOCALS",6)
	See(ThirdNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY14)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY12)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BD_BreachW","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		UseItem("WAND18",LastSeenBy(Myself))  // 法术重击之杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_BreachW","LOCALS",6)
	See(FourthNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY14)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY12)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BD_BreachW","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		UseItem("WAND18",LastSeenBy(Myself))  // 法术重击之杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_BreachW","LOCALS",6)
	See(FifthNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY14)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY12)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BD_BreachW","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		UseItem("WAND18",LastSeenBy(Myself))  // 法术重击之杖
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("BD_Cast","LOCALS")
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!GlobalTimerNotExpired("BD_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // 法术重击之杖
	GlobalLT("BD_BreachW","LOCALS",6)
	See(SixthNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY14)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY5)
		CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY12)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("BD_BreachW","LOCALS",1)
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("BD_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // 使用一柄法杖
		UseItem("WAND18",LastSeenBy(Myself))  // 法术重击之杖
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
	See([GOODCUTOFF])
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
		ForceSpellRES("SPWI902",LastSeenBy(Myself))  // spwi429.spl (魔邓肯魔力飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
		ForceSpellRES("SPWI902",LastSeenBy(Myself))  // spwi429.spl (魔邓肯魔力飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
		ForceSpellRES("SPWI902",LastSeenBy(Myself))  // spwi429.spl (魔邓肯魔力飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
		ForceSpellRES("SPWI902",LastSeenBy(Myself))  // spwi429.spl (魔邓肯魔力飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
		ForceSpellRES("SPWI902",LastSeenBy(Myself))  // spwi429.spl (魔邓肯魔力飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_SKULL_TRAP)  // SPWI313.SPL (寻找陷阱)
		ForceSpellRES("SPWI902",LastSeenBy(Myself))  // spwi429.spl (魔邓肯魔力飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See([GOODCUTOFF])
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (降低抗性)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("SCRL9L",Myself)  // 法术重击
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	!CheckStatGT(Myself,0,SCRIPTINGSTATE9)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		SetInterrupt(FALSE)
		DestroyItem("SCRL9L")  // 法术重击
		DisplayStringHead(Myself,46153)  // 使用卷轴
		SpellNoDec(Myself,WIZARD_SPELL_TRAP)  // SPWI902.SPL (七级召唤怪物术)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (火焰护盾（红）)
	CheckStat(Myself,0,EXTRAPROFICIENCY11)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (火焰护盾（红）)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (冰风暴)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTCOLD)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)  // SPWI404.SPL (冰风暴)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (冰风暴)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTCOLD)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)  // SPWI404.SPL (冰风暴)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ICE_STORM)  // SPWI404.SPL (冰风暴)
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTCOLD)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ICE_STORM)  // SPWI404.SPL (冰风暴)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("BD_TStop","LOCALS")
	HaveSpell(WIZARD_ANIMATE_DEAD)  // SPWI501.SPL (操纵死尸)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	Range([GOODCUTOFF],30)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_ANIMATE_DEAD)  // SPWI501.SPL (操纵死尸)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // 魔法屏蔽斗篷
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (马友夫强酸箭)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	OR(2)
		!GlobalTimerNotExpired("BD_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,EXTRAPROFICIENCY6)
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // 竖琴手别针
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // 流浪剑客的胸针
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE5)
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE9)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY2)
	!CheckStatGT(LastSeenBy(Myself),0,EXTRAPROFICIENCY15)
	!CheckStat(LastSeenBy(Myself),1,EXTRAPROFICIENCY9)
	!CheckStat(LastSeenBy(Myself),6,SCRIPTINGSTATE7)
THEN
	RESPONSE #100
		SetGlobalTimer("BD_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (魔法飞弹)
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
	Range(LastSeenBy(Myself),3)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackOneRound(NearestEnemyOf(Myself))
END

IF
	HasItem("eneblade",Myself)  // 魔能刃
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("eneblade",Myself)  // 魔能刃
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("eneblade",Myself)  // 魔能刃
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("eneblade",Myself)  // 魔能刃
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("eneblade",Myself)  // 魔能刃
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	HasItem("eneblade",Myself)  // 魔能刃
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	!CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
	RESPONSE #100
		AttackOneRound(LastSeenBy(Myself))
END

IF
	!Detect([PC])
	!Detect([GOODCUTOFF])
	ActionListEmpty()
	InMyArea(Player1)
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Myself,STATE_HELPLESS)
	!StateCheck(Myself,STATE_CONFUSED)
	!StateCheck(Myself,STATE_STUNNED)
	!StateCheck(Myself,STATE_PANIC)
	!StateCheck(Myself,STATE_CHARMED)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

