IF
	TriggerOverride(Player1,PersonalSpaceDistance([GOODCUTOFF],0))
	RandomNum(6,1)
THEN
	RESPONSE #100
		ActionOverride(Player1,JumpToObject(Myself))
		Continue()
END

IF
	TriggerOverride(Player2,PersonalSpaceDistance([GOODCUTOFF],0))
	RandomNum(6,2)
THEN
	RESPONSE #100
		ActionOverride(Player2,JumpToObject(Myself))
		Continue()
END

IF
	TriggerOverride(Player3,PersonalSpaceDistance([GOODCUTOFF],0))
	RandomNum(6,3)
THEN
	RESPONSE #100
		ActionOverride(Player3,JumpToObject(Myself))
		Continue()
END

IF
	TriggerOverride(Player4,PersonalSpaceDistance([GOODCUTOFF],0))
	RandomNum(6,4)
THEN
	RESPONSE #100
		ActionOverride(Player4,JumpToObject(Myself))
		Continue()
END

IF
	TriggerOverride(Player5,PersonalSpaceDistance([GOODCUTOFF],0))
	RandomNum(6,5)
THEN
	RESPONSE #100
		ActionOverride(Player5,JumpToObject(Myself))
		Continue()
END

IF
	TriggerOverride(Player6,PersonalSpaceDistance([GOODCUTOFF],0))
	RandomNum(6,6)
THEN
	RESPONSE #100
		ActionOverride(Player6,JumpToObject(Myself))
		Continue()
END

