IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(NearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(NearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(NearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(NearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(NearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(NearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(NearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(NearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(NearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(NearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SecondNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SecondNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SecondNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SecondNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SecondNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SecondNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(SecondNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(ThirdNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(FourthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(FourthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(FourthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(FourthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(FourthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(FourthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(FourthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(FifthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(FifthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(FifthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(FifthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(FifthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(FifthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(FifthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SixthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SixthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SixthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SixthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SixthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SixthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(SixthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(SeventhNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(EighthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(EighthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(EighthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(EighthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(EighthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(EighthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(EighthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(NinthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(NinthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(NinthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(NinthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(NinthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(NinthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(NinthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(TenthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(TenthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]))
	TriggerOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.MAGE_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(TenthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(TenthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]))
	TriggerOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.THIEF_ALL]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

IF
	OR(2)
		Global("LZIMAGAI","GLOBAL",1)
		Global("LZIMAGAI","GLOBAL",3)
	!CheckStat(TenthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),3,PUPPETMASTERTYPE)
	ObjectActionListEmpty(TenthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]))
	TriggerOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),Global("ENEMY_SIMULA","LOCALS",0))
THEN
	RESPONSE #100
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),SetGlobal("ENEMY_SIMULA","LOCALS",1))
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),DisplayString(Myself,46153))  // 使用卷轴
		ActionOverride(TenthNearestEnemyOfType([EVILCUTOFF.0.0.BARD]),ForceSpellRES("LZWI804",Myself))  // 拟象术
		Continue()
END

