IF
	ActionListEmpty()
	Class(Myself,BARD)
	!ModalState(BATTLESONG)
	OR(2)
		See(NearestEnemyOf(Myself))
		CombatCounterGT(0)
	HasItemEquiped("BDHELM11",Myself)  // 诗人之帽
THEN
	RESPONSE #100
		BattleSong()
END

IF
	ActionListEmpty()
	Class(Myself,BARD)
	ModalState(BATTLESONG)
	OR(2)
		See(NearestEnemyOf(Myself))
		CombatCounterGT(0)
	HasItemEquiped("BDHELM11",Myself)  // 诗人之帽
	!GlobalTimerNotExpired("AttackDuringSong","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("AttackDuringSong","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,11798)  // 吟唱歌曲
END

IF
	ActionListEmpty()
	Class(Myself,BARD)
	ModalState(BATTLESONG)
	!See(NearestEnemyOf(Myself))
	CombatCounter(0)
	Delay(30)
THEN
	RESPONSE #100
		ClearActions(Myself)
END

IF
	ActionListEmpty()
	IsWeaponRanged(Myself)
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),6)
THEN
	RESPONSE #100
		RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	See(NearestEnemyOf(Myself))
	WeaponEffectiveVs(NearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(NearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	See(SecondNearestEnemyOf(Myself))
	WeaponEffectiveVs(SecondNearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(SecondNearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackReevaluate(SecondNearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	See(ThirdNearestEnemyOf(Myself))
	WeaponEffectiveVs(ThirdNearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(ThirdNearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackReevaluate(ThirdNearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	See(FourthNearestEnemyOf(Myself))
	WeaponEffectiveVs(FourthNearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(FourthNearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackReevaluate(FourthNearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	See(FifthNearestEnemyOf(Myself))
	WeaponEffectiveVs(FifthNearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(FifthNearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackReevaluate(FifthNearestEnemyOf(Myself),30)
END

IF
	ActionListEmpty()
	See(SixthNearestEnemyOf(Myself))
	WeaponEffectiveVs(SixthNearestEnemyOf(Myself),MAINHAND)
	WeaponCanDamage(SixthNearestEnemyOf(Myself),MAINHAND)
THEN
	RESPONSE #100
		AttackReevaluate(SixthNearestEnemyOf(Myself),30)
END

